# ============================================================
# FcapBpaHCR_ane
#
# Annual management procedure for anchovy 9a South.
#
# The function receives the perceived FLStock generated by the
# observation/assessment component and produces annual TAC advice
# using an Fcap + Bescapement harvest-control rule.
#
# Management sequence:
#
#   perceived stock at assessment year
#        ↓
#   project abundance to Q1 of TAC year
#        ↓
#   reconstruct SS3-like seasonal population dynamics
#        ↓
#   calculate spawning biomass at start of Q2
#        ↓
#   apply Beverton-Holt recruitment at start of Q3
#        ↓
#   search F within [0,Fcap] subject to SSB >= Bescapement
#        ↓
#   convert selected F into annual realised catch (TAC)
#
# The projection follows the seasonal timing validated against
# the SS3 forecast:
#
#   Q1 survival
#   Q2 spawning biomass
#   Q3 recruitment
#   Q4 survival
#   annual ageing and 3+ plus group
#
# Fishing mortality is represented as:
#
#   F[a,s] = Fbase * propf[s] * Frel[a,s] * dt
#
# where:
#   Fbase = annualised fishing-mortality target
#   propf = seasonal allocation of annual F
#   Frel  = relative F-at-age pattern within each season
#   dt    = seasonal duration (0.25)
#
# ============================================================

FcapBpaHCR_ane <- function(stocks, advice, advice.ctrl, year, stknm, ...) {
  
  # ============================================================
  # HELPER FUNCTIONS
  # ============================================================
  
  # ------------------------------------------------------------
  # get_ctrl()
  #
  # Extract a control parameter from advice.ctrl.
  #
  # If the parameter is NULL, return the specified default value.
  # Used to keep optional MP controls explicit and compact.
  # ------------------------------------------------------------
  
  get_ctrl <- function(x,default=NULL) {
    if (is.null(x)) return(default)
    x
  }
  
  
  # ------------------------------------------------------------
  # get_Fprop()
  #
  # Estimate the seasonal allocation of annual fishing mortality
  # from the perceived historical stock.
  #
  # For each of the last nFyears:
  #
  #   1. extract F-at-age for each season;
  #   2. define seasonal F as max F-at-age within that season;
  #   3. express seasonal F as a proportion of annual F.
  #
  # The final propf vector is the mean seasonal proportion across
  # the selected historical years, rescaled to sum to one.
  #
  # Output:
  #   vector of seasonal proportions:
  #
  #     propf[Q1] + ... + propf[Q4] = 1
  #
  # These proportions determine how Fbase is distributed among
  # quarters in the SS3-like projection.
  # ------------------------------------------------------------
  
  get_Fprop <- function(stk,ass.yr,nFyears,iter=1) {
    yrs <- as.numeric(dimnames(stk)$year)
    hist.yrs <- tail(yrs[yrs <= ass.yr],nFyears)
    
    if (length(hist.yrs) == 0) stop("get_Fprop: no years available to estimate seasonal F proportions.")
    
    Fprop_year <- sapply(hist.yrs,function(y) {
      F_y <- harvest(stk)[,as.character(y),,,,,iter]
      Fseason_y <- sapply(seq_len(dims(stk)$season),function(s) max(as.numeric(F_y[,,,s,,]),na.rm=TRUE))
      if (sum(Fseason_y) <= 0) return(rep(NA_real_,length(Fseason_y)))
      Fseason_y/sum(Fseason_y)
    })
    
    Fprop <- rowMeans(Fprop_year,na.rm=TRUE)
    Fprop/sum(Fprop)
  }
  
  
  # ------------------------------------------------------------
  # project_ss3_one_year()
  #
  # Project one management year using SS3-like seasonal dynamics.
  #
  # The function reproduces the timing validated independently
  # against the SS3 forecast:
  #
  #   start Q1 : N-at-age available
  #   Q1       : survival and catch
  #   start Q2 : spawning biomass
  #   Q2       : survival and catch
  #   start Q3 : Beverton-Holt recruitment enters age 0
  #   Q3       : survival and catch
  #   Q4       : survival and catch
  #   end Q4   : ageing to next-year Q1 and formation of 3+ group
  #
  # Fishing mortality:
  #
  #   Fseason[s] = Fbase * propf[s]
  #
  #   F[a,s] = Fseason[s] * Frel[a,s] * dt
  #
  # when M is already stored at seasonal scale.
  #
  # Recruitment:
  #
  #   R = a * SSB / (b + SSB)
  #
  # Catch is calculated with the Baranov equation.
  #
  # Inputs:
  #   N_Q1       numbers-at-age at start of Q1
  #   M          natural mortality by age and season
  #   Frel       relative F-at-age pattern by season
  #   W_spawn    reproductive weight-at-age in Q2
  #   W_catch    catch weight-at-age by season
  #   Fbase      annualised F target
  #   propf      seasonal allocation of F
  #   a, b       Beverton-Holt parameters
  #
  # Output:
  #   complete one-year projection including SSB, recruitment,
  #   catch, seasonal F and next-year abundance.
  # ------------------------------------------------------------
  
  project_ss3_one_year <- function(N_Q1,M,Frel,W_spawn,W_catch,Fbase,propf,a,b,dt=0.25,M_is_seasonal=FALSE) {
    
    ages <- names(N_Q1)
    seasons <- seq_len(ncol(Frel))
    Fseason <- Fbase*propf
    
    N <- matrix(0,nrow=length(ages),ncol=length(seasons),dimnames=list(age=ages,season=seasons))
    Fage <- matrix(0,nrow=length(ages),ncol=length(seasons),dimnames=list(age=ages,season=seasons))
    Z <- matrix(0,nrow=length(ages),ncol=length(seasons),dimnames=list(age=ages,season=seasons))
    catch_num <- matrix(0,nrow=length(ages),ncol=length(seasons),dimnames=list(age=ages,season=seasons))
    catch_bio <- numeric(length(seasons))
    
    get_Ms <- function(s) if (M_is_seasonal) M[,s] else M
    get_dt <- function() if (M_is_seasonal) 1 else dt
    
    N[,1] <- N_Q1
    dts <- get_dt()
    
    Ms <- get_Ms(1)
    Fage[,1] <- Fseason[1]*Frel[,1]
    Z[,1] <- Ms+Fage[,1]
    catch_num[,1] <- N[,1]*(Fage[,1]/Z[,1])*(1-exp(-Z[,1]*dts))
    catch_bio[1] <- sum(catch_num[,1]*W_catch[,1])
    N[,2] <- N[,1]*exp(-Z[,1]*dts)
    
    SSB_Q2 <- sum(N[,2]*W_spawn)
    R_Q3 <- a*SSB_Q2/(b+SSB_Q2)
    
    Ms <- get_Ms(2)
    Fage[,2] <- Fseason[2]*Frel[,2]
    Z[,2] <- Ms+Fage[,2]
    catch_num[,2] <- N[,2]*(Fage[,2]/Z[,2])*(1-exp(-Z[,2]*dts))
    catch_bio[2] <- sum(catch_num[,2]*W_catch[,2])
    N[,3] <- N[,2]*exp(-Z[,2]*dts)
    N["0",3] <- R_Q3
    
    Ms <- get_Ms(3)
    Fage[,3] <- Fseason[3]*Frel[,3]
    Z[,3] <- Ms+Fage[,3]
    catch_num[,3] <- N[,3]*(Fage[,3]/Z[,3])*(1-exp(-Z[,3]*dts))
    catch_bio[3] <- sum(catch_num[,3]*W_catch[,3])
    N[,4] <- N[,3]*exp(-Z[,3]*dts)
    
    Ms <- get_Ms(4)
    Fage[,4] <- Fseason[4]*Frel[,4]
    Z[,4] <- Ms+Fage[,4]
    catch_num[,4] <- N[,4]*(Fage[,4]/Z[,4])*(1-exp(-Z[,4]*dts))
    catch_bio[4] <- sum(catch_num[,4]*W_catch[,4])
    
    N_endQ4 <- N[,4]*exp(-Z[,4]*dts)
    N_next_Q1 <- c(`0`=0,`1`=unname(N_endQ4["0"]),`2`=unname(N_endQ4["1"]),`3`=unname(N_endQ4["2"]+N_endQ4["3"]))
    
    list(Fbase=Fbase,Fseason=Fseason,N=N,Fage=Fage,Z=Z,SSB_Q2=SSB_Q2,R_Q3=R_Q3,
         catch_num=catch_num,catch_bio=catch_bio,TAC=sum(catch_bio),N_endQ4=N_endQ4,N_next_Q1=N_next_Q1)
  }
  
  
  # ------------------------------------------------------------
  # get_N_next_Q1()
  #
  # Reconstruct numbers-at-age at the start of the TAC year.
  #
  # Starting from Q4 of the assessment year, apply Q4 mortality
  # and then perform annual ageing:
  #
  #   age 0 -> age 1
  #   age 1 -> age 2
  #   age 2 + age 3 -> age 3+
  #
  # Age 0 is set to zero at Q1 because recruitment enters at the
  # start of Q3 in the anchovy SS3 model.
  #
  # Output:
  #   N-at-age vector at start of Q1 of the TAC year.
  # ------------------------------------------------------------
  
  get_N_next_Q1 <- function(stk,ass.yr.name,iter=1) {
    ages <- dimnames(stock.n(stk))$age
    s4 <- as.character(max(as.integer(dimnames(stock.n(stk))$season)))
    
    N_Q4 <- setNames(as.numeric(stock.n(stk)[,ass.yr.name,,s4,,iter]),ages)
    M_Q4 <- setNames(as.numeric(m(stk)[,ass.yr.name,,s4,,iter]),ages)
    F_Q4 <- setNames(as.numeric(harvest(stk)[,ass.yr.name,,s4,,iter]),ages)
    
    N_endQ4 <- N_Q4*exp(-(M_Q4+F_Q4))
    
    N_next_Q1 <- setNames(rep(0,length(ages)),ages)
    N_next_Q1["0"] <- 0
    N_next_Q1["1"] <- N_endQ4["0"]
    N_next_Q1["2"] <- N_endQ4["1"]
    N_next_Q1["3"] <- N_endQ4["2"]+N_endQ4["3"]
    
    N_next_Q1
  }
  
  
  # ------------------------------------------------------------
  # get_Frel()
  #
  # Derive the relative F-at-age pattern within each season from
  # catchability.
  #
  # catch.q is normalized independently within each quarter:
  #
  #   Frel[a,s] = q[a,s] / max_a(q[a,s])
  #
  # Therefore max(Frel[,s]) = 1 for every season.
  #
  # This removes the absolute fishing-intensity component and
  # retains only the age-specific within-season fishing pattern.
  #
  # The use of normalized catch.q was previously validated
  # against realised F-at-age reconstructed independently with
  # the Baranov equation.
  # ------------------------------------------------------------
  
  get_Frel <- function(catch.q,year,iter=1) {
    ages <- dimnames(catch.q)$age
    seasons <- dimnames(catch.q)$season
    
    Frel <- matrix(NA_real_,nrow=length(ages),ncol=length(seasons),dimnames=list(age=ages,season=seasons))
    
    for (s in seq_along(seasons)) {
      q <- as.numeric(catch.q[,as.character(year),,seasons[s],,iter])
      qmax <- max(q,na.rm=TRUE)
      if (!is.finite(qmax) || qmax <= 0) stop("get_Frel: non-positive catch.q in year ",year,", season ",seasons[s],".")
      Frel[,s] <- q/qmax
    }
    
    Frel
  }
  
  
  # ------------------------------------------------------------
  # get_SRpars()
  #
  # Extract the Beverton-Holt parameters used by the one-year
  # projection.
  #
  # Parameters a and b are taken from the FLSRsim object for the
  # TAC year, recruitment season and OM iteration.
  #
  # Recruitment is then calculated as:
  #
  #   R = a * SSB / (b + SSB)
  #
  # Output:
  #   named vector c(a,b).
  # ------------------------------------------------------------
  
  get_SRpars <- function(sr,year,rec.season,iter=1) {
    pars <- sr@params
    a <- as.numeric(pars["a",as.character(year),as.character(rec.season),iter])
    b <- as.numeric(pars["b",as.character(year),as.character(rec.season),iter])
    
    if (!is.finite(a) || !is.finite(b)) {
      stop("get_SRpars: non-finite Beverton-Holt parameters.")
    }
    
    c(a=a,b=b)
  }
  
  
  # ------------------------------------------------------------
  # get_F_HCR()
  #
  # Apply the Fcap + Bescapement harvest-control rule.
  #
  # The rule evaluates projected spawning biomass under two
  # boundary fishing scenarios:
  #
  #   F = 0
  #   F = Fcap
  #
  # Three outcomes are possible:
  #
  #   1. SSB(Fcap) >= Besc
  #        -> retain Fcap
  #
  #   2. SSB(0) < Besc
  #        -> closure, F = 0
  #
  #   3. SSB(0) >= Besc and SSB(Fcap) < Besc
  #        -> solve for the intermediate F such that
  #
  #             SSB(F) = Besc
  #
  #      using uniroot().
  #
  # The selected F is projected through project_ss3_one_year()
  # and converted into the corresponding annual catch advice.
  #
  # Output:
  #   F        selected annualised F
  #   TAC      resulting annual catch
  #   SSB_Q2   projected spawning biomass
  #   R_Q3     projected recruitment
  #   projection complete one-year projection object
  # ------------------------------------------------------------
  
  get_F_HCR <- function(N_Q1,M,Frel,W_spawn,W_catch,Fcap,Besc,propf,a,b,dt=0.25,M_is_seasonal=TRUE) {
    run_F <- function(F) project_ss3_one_year(N_Q1=N_Q1,M=M,Frel=Frel,W_spawn=W_spawn,W_catch=W_catch,Fbase=F,propf=propf,a=a,b=b,dt=dt,M_is_seasonal=M_is_seasonal)
    
    p0 <- run_F(0)
    pcap <- run_F(Fcap)
    
    if (pcap$SSB_Q2 >= Besc) {
      Fstar <- Fcap
      proj <- pcap
    } else if (p0$SSB_Q2 < Besc) {
      Fstar <- 0
      proj <- p0
    } else {
      obj <- function(F) run_F(F)$SSB_Q2-Besc
      Fstar <- uniroot(obj,c(0,Fcap))$root
      proj <- run_F(Fstar)
    }
    
    list(F=Fstar,TAC=proj$TAC,SSB_Q2=proj$SSB_Q2,R_Q3=proj$R_Q3,projection=proj)
  }
  
  # ============================================================
  # 1. EXTRACT MANAGEMENT-PROCEDURE CONTROLS
  #
  # Read all stock-specific settings required by the MP:
  #
  #   - biological timing
  #   - Fcap and escapement reference points
  #   - historical window used to estimate seasonal F allocation
  #   - assessment-error configuration
  #   - stock-recruitment model
  #   - catchability pattern
  #
  # ============================================================
  
  ctrl_stk <- advice.ctrl[[stknm]]
  
  if (is.null(ctrl_stk)) stop("FcapBpaHCR_ane: no control block found for stock ",stknm)
  
  nyears       <- get_ctrl(ctrl_stk$nyears,1)
  wts.nyears   <- get_ctrl(ctrl_stk$wts.nyears,3)
  fbar.nyears  <- get_ctrl(ctrl_stk$fbar.nyears,3)
  f.rescale    <- get_ctrl(ctrl_stk$f.rescale,TRUE)
  
  spawn.season <- get_ctrl(ctrl_stk$spawn.season,2)
  rec.season   <- get_ctrl(ctrl_stk$rec.season,3)
  Fcap         <- get_ctrl(ctrl_stk$Fcap,NA)
  nFyears      <- get_ctrl(ctrl_stk$nFyears,5)
  
  assessment.error <- get_ctrl(ctrl_stk$assessment.error,NULL)
  assess_error_R   <- get_ctrl(ctrl_stk$assess_error_R,FALSE)
  
  ref.pts     <- ctrl_stk$ref.pts
  sr          <- ctrl_stk$sr
  catch.q     <- ctrl_stk$catch.q
  diagnostics <- get_ctrl(ctrl_stk$diagnostics,FALSE)
  
  if (is.null(sr)) stop("FcapBpaHCR_ane: sr object is missing in advice.ctrl.")
  if (is.null(catch.q)) stop("FcapBpaHCR_ane: catch.q is missing in advice.ctrl.")
  if (length(Fcap) != 1 || !is.finite(Fcap) || Fcap < 0) stop("FcapBpaHCR_ane: Fcap must be one finite, non-negative scalar.")
  
  
  # ============================================================
  # 2. EXTRACT STOCK AND CHECK STRUCTURE
  #
  # Retrieve the FLStock received by annualTAC() and determine:
  #
  #   - number of seasons
  #   - number of iterations
  #
  # The anchovy MP assumes four seasonal steps, spawning in Q2
  # and recruitment entering in Q3.
  #
  # ============================================================
  
  if (inherits(stocks,"FLStock")) {
    stk <- stocks
  } else {
    stk <- stocks[[stknm]]
  }
  
  if (is.null(stk)) stop("FcapBpaHCR_ane: stock ",stknm," not found.")
  
  ns <- dims(stk)$season
  ni <- dims(stk)$iter
  
  if (spawn.season > ns) stop("FcapBpaHCR_ane: spawn.season is larger than number of seasons.")
  if (rec.season > ns) stop("FcapBpaHCR_ane: rec.season is larger than number of seasons.")
  if (length(nFyears) != 1 || !is.finite(nFyears) || nFyears < 1) stop("FcapBpaHCR_ane: nFyears must be one positive finite scalar.")
  
  
  # ============================================================
  # 3. DEFINE REFERENCE POINTS AND ESCAPEMENT TARGET
  #
  # Bpa is used as the default escapement threshold.
  # An alternative Besc can be supplied through advice.ctrl.
  #
  # Blim is retained as a biological reference point for
  # diagnostics and subsequent performance evaluation.
  #
  # ============================================================
  
  if (is.null(ref.pts)) stop("FcapBpaHCR_ane: ref.pts is missing.")
  if (!"Bpa" %in% rownames(ref.pts)) stop("FcapBpaHCR_ane: Bpa not found in ref.pts.")
  if (!"Blim" %in% rownames(ref.pts)) stop("FcapBpaHCR_ane: Blim not found in ref.pts.")
  
  Bescapement <- as.numeric(get_ctrl(ctrl_stk$Besc,ref.pts["Bpa",1]))
  Blim <- as.numeric(ref.pts["Blim",1])
  
  
  # ============================================================
  # 4. DEFINE ASSESSMENT YEAR AND TAC YEAR
  #
  # FLBEIA passes the assessment year as a positional index.
  # The MP uses information available in the assessment year
  # to generate advice for the following TAC year.
  #
  # ============================================================
  
  yrs.stk <- dimnames(stk)$year
  
  if (year < 1 || year > length(yrs.stk)) return(advice)
  
  ass.yr.name <- yrs.stk[year]
  ass.yr <- as.numeric(ass.yr.name)
  
  tac.yr <- ass.yr+1
  tac.yr.name <- as.character(tac.yr)
  
  if (!tac.yr.name %in% dimnames(advice$TAC)$year) return(advice)
  
  
  # ============================================================
  # 5. PREPARE TRUE AND PERCEIVED ASSESSMENT STOCK
  #
  # Restrict the stock to information available up to the
  # assessment year.
  #
  # stk_true:
  #   unmodified stock received from the observation component.
  #
  # stk:
  #   perceived stock used by the MP after applying assessment
  #   error.
  #
  # ============================================================
  
  stk <- window(stk,end=ass.yr)
  stk_true <- stk
  
  
  # ============================================================
  # 6. EXTRACT ASSESSMENT-ERROR MULTIPLIERS
  #
  # Default behaviour is perfect assessment:
  #
  #   multiplier = 1
  #
  # If assessment-error trajectories are supplied, the
  # year-specific correlated multipliers for SSB, F and R are
  # extracted for each iteration.
  #
  # ============================================================
  
  mult_SSB <- rep(1,ni)
  mult_F <- rep(1,ni)
  mult_R <- rep(1,ni)
  
  assessment_error_applied <- FALSE
  
  if (!is.null(assessment.error)) {
    
    mult_array <- assessment.error$multiplier
    
    if (is.null(mult_array)) stop("FcapBpaHCR_ane: assessment.error does not contain $multiplier.")
    
    if (ass.yr.name %in% dimnames(mult_array)$year) {
      
      n_error_iter <- dim(mult_array)[2]
      
      if (ni > n_error_iter) stop("FcapBpaHCR_ane: more stock iterations than assessment-error trajectories.")
      
      error_iter <- seq_len(ni)
      
      mult_SSB <- as.numeric(mult_array[ass.yr.name,error_iter,"SSB"])
      mult_F <- as.numeric(mult_array[ass.yr.name,error_iter,"F"])
      mult_R <- as.numeric(mult_array[ass.yr.name,error_iter,"R"])
      
      assessment_error_applied <- TRUE
    }
  }
  
  
  # ============================================================
  # 7. BUILD THE PERCEIVED STOCK
  #
  # Assessment error affects only the stock seen by the MP.
  # The true stock remains unchanged.
  #
  # SSB error:
  #   applied to mature abundance (age 1+).
  #
  # F error:
  #   applied multiplicatively to the full age-season harvest
  #   pattern.
  #
  # Recruitment error:
  #   optional sensitivity component. When activated, age-0
  #   abundance is perturbed from Q3 onwards.
  #
  # ============================================================
  
  if (assessment_error_applied) {
    
    ages <- dimnames(stock.n(stk))$age
    seasons <- dimnames(stock.n(stk))$season
    
    mature_ages <- setdiff(ages,"0")
    rec_and_after <- seasons[as.integer(seasons) >= rec.season]
    
    for (i in seq_len(ni)) {
      
      stock.n(stk)[mature_ages,ass.yr.name,,,,i] <- stock.n(stk_true)[mature_ages,ass.yr.name,,,,i]*mult_SSB[i]
      
      if (assess_error_R) {
        stock.n(stk)["0",ass.yr.name,,rec_and_after,,i] <- stock.n(stk_true)["0",ass.yr.name,,rec_and_after,,i]*mult_R[i]
      }
      
      harvest(stk)[,ass.yr.name,,,,i] <- harvest(stk_true)[,ass.yr.name,,,,i]*mult_F[i]
    }
  }
  
  if (diagnostics && assessment_error_applied) {
    message(
      "Assessment error ",ass.yr.name,
      " | SSB mult median=",round(median(mult_SSB),3),
      " | F mult median=",round(median(mult_F),3),
      if (assess_error_R) paste0(" | R mult median=",round(median(mult_R),3)) else ""
    )
  }
  
  
  # ============================================================
  # 8. DERIVE FISHING-MORTALITY PATTERN USED BY THE MP
  #
  # Two complementary quantities are required:
  #
  # propf:
  #   seasonal distribution of annual F, estimated from recent
  #   perceived historical harvest.
  #
  # Frel:
  #   relative F-at-age pattern within each season, derived from
  #   normalised catchability.
  #
  # Both components were previously validated against realised
  # F-at-age from the FLBEIA operating model.
  #
  # ============================================================
  
  propf_iter <- t(sapply(seq_len(ni),function(i) get_Fprop(stk,ass.yr,nFyears,iter=i)))
  colnames(propf_iter) <- paste0("Q",seq_len(ns))
  
  if (any(!is.finite(propf_iter))) stop("FcapBpaHCR_ane: non-finite seasonal F proportions.")
  if (any(propf_iter < 0)) stop("FcapBpaHCR_ane: negative seasonal F proportions.")
  if (any(abs(rowSums(propf_iter)-1) > 1e-10)) stop("FcapBpaHCR_ane: seasonal F proportions do not sum to 1.")
  
  Frel_iter <- lapply(seq_len(ni),function(i) get_Frel(catch.q,ass.yr,iter=i))
  
  if (any(vapply(Frel_iter,function(x) any(!is.finite(x)),logical(1)))) stop("FcapBpaHCR_ane: non-finite Frel.")
  
  
  # ============================================================
  # 9. PROJECT ABUNDANCE TO START OF Q1 OF TAC YEAR
  #
  # Starting from Q4 of the perceived assessment stock:
  #
  #   - apply Q4 survival
  #   - age the population
  #   - form the 3+ plus group
  #   - set age 0 to zero because recruitment enters in Q3
  #
  # ============================================================
  
  N_Q1_iter <- lapply(seq_len(ni),function(i) get_N_next_Q1(stk,ass.yr.name,iter=i))
  
  
  # ============================================================
  # 10. EXTEND BIOLOGICAL INPUTS TO THE TAC YEAR
  #
  # stf() is used only to extend biological quantities required
  # by the SS3-like projection:
  #
  #   - natural mortality
  #   - catch weight-at-age
  #   - spawning weight-at-age
  #
  # Population dynamics and HCR evaluation are NOT performed by
  # FLasher::fwd().
  #
  # ============================================================
  
  stk <- FLasher::stf(
    stk,
    nyears=nyears,
    wts.nyears=wts.nyears,
    fbar.nyears=fbar.nyears,
    f.rescale=f.rescale)
  
  if (!tac.yr.name %in% dimnames(stk)$year) stop("FcapBpaHCR_ane: stf() did not generate TAC year ",tac.yr.name)
  
  
  # ============================================================
  # 11. EXTRACT BIOLOGICAL INPUTS FOR SS3-LIKE PROJECTION
  #
  # For each iteration extract:
  #
  #   M          seasonal natural mortality
  #   W_catch    catch weight-at-age by season
  #   W_spawn    stock.wt * maturity in spawning season
  #   a, b       Beverton-Holt parameters
  #
  # These quantities, together with N_Q1, propf and Frel, define
  # the one-year forecast used by the HCR.
  #
  # ============================================================
  
  M_iter <- lapply(seq_len(ni),function(i) {
    x <- matrix(as.numeric(m(stk)[,tac.yr.name,,,,i]),nrow=length(dimnames(stk)$age),ncol=ns)
    dimnames(x) <- list(age=dimnames(stk)$age,season=seq_len(ns))
    x
  })
  
  W_catch_iter <- lapply(seq_len(ni),function(i) {
    x <- matrix(as.numeric(catch.wt(stk)[,tac.yr.name,,,,i]),nrow=length(dimnames(stk)$age),ncol=ns)
    dimnames(x) <- list(age=dimnames(stk)$age,season=seq_len(ns))
    x
  })
  
  W_spawn_iter <- lapply(seq_len(ni),function(i) {
    setNames(
      as.numeric(stock.wt(stk)[,tac.yr.name,,spawn.season,,i]*mat(stk)[,tac.yr.name,,spawn.season,,i]),
      dimnames(stk)$age)
  })
  
  SRpars_iter <- lapply(seq_len(ni),function(i) get_SRpars(sr,tac.yr,rec.season,iter=i))
  
  a_iter <- vapply(SRpars_iter,function(x) x["a"],numeric(1))
  b_iter <- vapply(SRpars_iter,function(x) x["b"],numeric(1))
  
  
  # ============================================================
  # 12. OPTIONAL INPUT DIAGNOSTICS
  #
  # Print only when diagnostics = TRUE.
  # These messages are intended to verify the information entering
  # the HCR without flooding the closed-loop simulation output.
  #
  # ============================================================
  
  if (diagnostics) {
    message("")
    message("--- MP INPUTS ",ass.yr.name," -> ",tac.yr.name," ---")
    message("F seasonal proportions iter 1 = ",paste(round(propf_iter[1,],4),collapse=", "))
    message("Frel iter 1 = ",paste(apply(Frel_iter[[1]],2,function(x) paste(round(x,4),collapse=",")),collapse=" | "))
    message("N Q1 iter 1 = ",paste(round(N_Q1_iter[[1]],1),collapse=", "))
    message("M Q1 iter 1 = ",paste(round(M_iter[[1]][,1],4),collapse=", "))
    message("W spawn iter 1 = ",paste(round(W_spawn_iter[[1]],6),collapse=", "))
    message("BH iter 1: a=",round(a_iter[1],2)," | b=",round(b_iter[1],2))
  }
  
  # ============================================================
  # 13. APPLY FCAP + BESCAPEMENT HCR
  #
  # Apply the harvest-control rule independently to each
  # iteration using the perceived stock and the SS3-like
  # one-year projection.
  #
  # For each iteration the rule:
  #
  #   - projects SSB under F = 0 and F = Fcap
  #   - retains Fcap when SSB(Fcap) >= Besc
  #   - closes the fishery when SSB(0) < Besc
  #   - otherwise solves for F such that SSB(F) = Besc
  #
  # The selected F is converted directly into annual TAC through
  # the validated SS3-like seasonal projection.
  #
  # ============================================================
  
  HCR_iter <- lapply(seq_len(ni),function(i) {
    get_F_HCR(
      N_Q1=N_Q1_iter[[i]],
      M=M_iter[[i]],
      Frel=Frel_iter[[i]],
      W_spawn=W_spawn_iter[[i]],
      W_catch=W_catch_iter[[i]],
      Fcap=Fcap,
      Besc=Bescapement,
      propf=propf_iter[i,],
      a=a_iter[i],
      b=b_iter[i],
      dt=0.25,
      M_is_seasonal=TRUE)
  })
  
  Fbase <- vapply(HCR_iter,function(x) x$F,numeric(1))
  res_catch <- vapply(HCR_iter,function(x) x$TAC,numeric(1))
  SSB_HCR <- vapply(HCR_iter,function(x) x$SSB_Q2,numeric(1))
  R_HCR <- vapply(HCR_iter,function(x) x$R_Q3,numeric(1))
  
  if (any(!is.finite(Fbase))) stop("FcapBpaHCR_ane: non-finite F advice.")
  if (any(Fbase < 0 | Fbase > Fcap+1e-10)) stop("FcapBpaHCR_ane: F advice outside [0,Fcap].")
  if (any(!is.finite(res_catch) | res_catch < 0)) stop("FcapBpaHCR_ane: invalid TAC.")
  
  hcr_case <- ifelse(Fbase <= 1e-10,"closure",
                     ifelse(abs(Fbase-Fcap) <= 1e-10,"Fcap","reduced"))
  
  message(
    "HCR ",ass.yr.name," -> ",tac.yr.name,
    " | F median=",round(median(Fbase),3),
    " | TAC median=",round(median(res_catch),0)," t",
    " | Besc=",round(Bescapement,0)," t"
  )
  
  if (diagnostics) {
    message(
      "HCR branches | closure=",sum(hcr_case=="closure"),
      " | reduced F=",sum(hcr_case=="reduced"),
      " | Fcap=",sum(hcr_case=="Fcap"),
      " / ",ni
    )
  }
  
  # ============================================================
  # 14. WRITE MANAGEMENT ADVICE
  #
  # Store the annual TAC and corresponding annualised F selected
  # by the HCR for each iteration.
  #
  # ============================================================
  
  advice$TAC[stknm,tac.yr.name] <- res_catch
  
  if (is.null(advice$Fadv)) {
    advice$Fadv <- advice$TAC
    advice$Fadv[] <- NA
    units(advice$Fadv) <- "f"
  }
  
  advice$Fadv[stknm,tac.yr.name] <- Fbase
  
  
  
  if (diagnostics) {
    return(list(
      advice=advice,
      stk=stk,
      ass.yr.name=ass.yr.name,
      tac.yr.name=tac.yr.name,
      Fcap=Fcap,
      Blim=Blim,
      Bescapement=Bescapement,
      propf_iter=propf_iter,
      Frel_iter=Frel_iter,
      N_Q1_iter=N_Q1_iter,
      M_iter=M_iter,
      W_catch_iter=W_catch_iter,
      W_spawn_iter=W_spawn_iter,
      a_iter=a_iter,
      b_iter=b_iter,
      HCR_iter=HCR_iter,
      Fbase=Fbase,
      TAC=res_catch,
      SSB_HCR=SSB_HCR,
      R_HCR=R_HCR,
      hcr_case=hcr_case
    ))
  }
  
  return(advice)
}

environment(FcapBpaHCR_ane) <- asNamespace("FLBEIA")
assignInNamespace(x     = "annualTAC",value = FcapBpaHCR_ane, ns    = "FLBEIA")


