# ============================================================
# FCAP_BESC_CANDIDATE_RANGE_DIAGNOSTIC.R
# Diagnostic for candidate Besc range
# Probabilistic Fcap + Besc management procedure
# Anchovy 9a South
#
# Purpose:
#   Characterise the biological and operational implications
#   of alternative escapement biomass thresholds before the
#   closed-loop MSE.
#
# This script DOES NOT select an optimal Besc.
# It defines and characterises a plausible candidate range.
#
# The diagnostic considers:
#   1. Besc relative to stock-specific biomass reference points.
#   2. Alternative reference-point values examined at WKBANSP.
#   3. Expected forecast SSB required to satisfy:
#
#      P(SSBforecast < Besc) <= alpha
#
#      equivalently:
#
#      Q_alpha(SSBforecast) >= Besc
#
#   4. Three forecast-uncertainty scenarios:
#      S0 = deterministic forecast
#      S1 = current assessment uncertainty
#      S2 = contemporary bootstrap uncertainty
#
# No FLBEIA simulation is run here.
# ============================================================

rm(list=ls())

# ============================================================
# LOAD LIBRARIES
# ============================================================

library(dplyr)
library(tidyr)
library(purrr)
library(ggplot2)
library(here)

# ============================================================
# DIRECTORIES
# ============================================================

rds_dir <- here("data","Rdata")
out_dir <- here("outputs","mse","Besc_candidate_range")
fig_dir <- file.path(out_dir,"figures")
dir.create(out_dir,recursive=TRUE,showWarnings=FALSE)
dir.create(fig_dir,recursive=TRUE,showWarnings=FALSE)

# ============================================================
# CURRENT MSE REFERENCE POINTS
# ============================================================

Blim <- 4721
Bpa <- 6561

# ============================================================
# WKBANSP REFERENCE-POINT CONTEXT
#
# Reference points and short-term forecast for WKBANSP 2024
#
# B0    = 16865 t
# Bloss = 6552.06 t
#
# Alternative Blim calculations evaluated:
#
#   0.2 * B0                         = 3373 t
#   Bpa * exp(-1.645 * 0.30)        = 4000 t
#   Bpa * exp(-1.645 * 0.20)        = 4715 t
#   Bpa * exp(-1.645 * 0.10)        = 5542 t
#   Bloss                            = 6552 t
#
# The recommended WKBANSP value was Blim = 4715 t,
# using Bpa = Bloss and sigmaB = 0.20.
#
# Current MSE values (Blim=4721; Bpa=6561) are retained
# operationally and are not replaced by the WKBANSP values.
# ============================================================

B0_WKBANSP <- 16865
Bloss_WKBANSP <- 6552.06
Blim_02B0 <- 3373
Blim_sigma030 <- 4000
Blim_sigma020 <- 4715
Blim_sigma010 <- 5542
Bpa_WKBANSP <- Bloss_WKBANSP

# ============================================================
# REFERENCE-POINT TABLE
# ============================================================

reference_points <- tibble(
  reference=c("0.2 B0","Blim sigmaB=0.30","Blim sigmaB=0.20","Current MSE Blim","Blim sigmaB=0.10","WKBANSP Bloss/Bpa","Current MSE Bpa"),
  value=c(Blim_02B0,Blim_sigma030,Blim_sigma020,Blim,Blim_sigma010,Bpa_WKBANSP,Bpa),
  source=c("WKBANSP 2024","WKBANSP 2024","WKBANSP 2024","Current MSE","WKBANSP 2024","WKBANSP 2024","Current MSE"),
  role=c("Alternative Blim","Alternative Blim","Recommended WKBANSP Blim","Operational Blim","Alternative Blim","WKBANSP Bpa","Operational Bpa")
)

reference_points <- reference_points %>%
  arrange(value)

print(reference_points,n=Inf)

# ============================================================
# CANDIDATE BESC VALUES
# ============================================================

Besc_candidates <- c(5000,6561,8000,10000)

# ============================================================
# DIAGNOSTIC BESC GRID
#
# This fine grid is used only to characterise the response.
#
# It extends below the candidate range so that all alternative
# stock-specific reference points evaluated at WKBANSP are
# visible in the diagnostic.
#
# It is NOT the candidate MP grid.
# ============================================================

Besc_grid <- seq(3000,10000,by=50)

Besc_grid <- sort(unique(c(Besc_grid,Besc_candidates,reference_points$value)))

# ============================================================
# PROBABILITY SETTINGS
# ============================================================

alpha <- 0.05
z_alpha <- qnorm(alpha)

stopifnot(alpha>0)
stopifnot(alpha<0.5)
stopifnot(Blim>0)
stopifnot(Bpa>Blim)
stopifnot(all(Besc_candidates>0))

# ============================================================
# FORECAST UNCERTAINTY INPUT
#
# Generated by:
# 15_SS3_FORECAST_UNCERTAINTY.R
# ============================================================

forecast_file <- file.path(rds_dir,"forecast_uncertainty_characterisation.rds")

stopifnot(file.exists(forecast_file))

forecast_uncertainty <- readRDS(forecast_file)

# ============================================================
# S1 — CURRENT ASSESSMENT UNCERTAINTY
# ============================================================

CV_S1 <- forecast_uncertainty$base$SSB_CV

if(is.null(CV_S1)) stop("S1 forecast CV not found in forecast uncertainty object.")

CV_S1 <- as.numeric(CV_S1)

stopifnot(length(CV_S1)==1)

stopifnot(is.finite(CV_S1))

stopifnot(CV_S1>=0)

# ============================================================
# S2 — CONTEMPORARY BOOTSTRAP UNCERTAINTY
# ============================================================

CV_S2 <- forecast_uncertainty$contemporary$SSB_2025_CV

if(is.null(CV_S2)) stop("S2 bootstrap forecast CV distribution not found.")

CV_S2 <- as.numeric(CV_S2)
CV_S2 <- CV_S2[is.finite(CV_S2)]
CV_S2 <- CV_S2[CV_S2>=0]

stopifnot(length(CV_S2)>0)
# ============================================================
# FORECAST UNCERTAINTY SUMMARY
# ============================================================

forecast_CV_summary <- tibble(
  scenario=c("S0","S1","S2"),
  description=c("Deterministic forecast","Current assessment uncertainty","Contemporary bootstrap uncertainty"),
  CV_median=c(0,CV_S1,median(CV_S2)),
  CV_p05=c(0,CV_S1,quantile(CV_S2,.05)),
  CV_p95=c(0,CV_S1,quantile(CV_S2,.95)),
  n=c(1,1,length(CV_S2))
)

print(forecast_CV_summary)

# ============================================================
# FUNCTION: REQUIRED EXPECTED SSB
# Assume:
# SSBforecast ~ Normal(mu,(CV * mu)^2)
# Therefore:
# Q_alpha = mu * (1 + z_alpha * CV)
# The escapement criterion is:
# Q_alpha >= Besc
# Thus:
# mu_required = Besc / (1 + z_alpha * CV)
# ============================================================

get_SSB_required <- function(Besc,CV,alpha=0.05) {
  
  if(CV==0) return(Besc)
  
  denominator <- 1+qnorm(alpha)*CV
  
  if(denominator<=0) return(Inf)
  
  Besc/denominator
}

# ============================================================
# BIOLOGICAL SCALE OF CANDIDATE BESC
# Ratios are calculated relative to the CURRENT MSE
# operational reference points.
# ============================================================

Besc_scale <- tibble(
  Besc=Besc_candidates,
  Besc_over_Blim=Besc_candidates/Blim,
  Besc_over_Bpa=Besc_candidates/Bpa,
  above_Blim=Besc_candidates-Blim,
  above_Bpa=Besc_candidates-Bpa
)

Besc_scale <- Besc_scale %>%
  mutate(reference_class=case_when(abs(Besc-Bpa)<1e-8 ~ "Bpa",Besc<Bpa ~ "Between Blim and Bpa",Besc>Bpa ~ "Above Bpa",TRUE ~ NA_character_))

print(Besc_scale)

# ============================================================
# ADD WKBANSP CONTEXT TO CANDIDATE TABLE
# ============================================================

Besc_context <- Besc_scale %>%
  mutate(Besc_over_B0=Besc/B0_WKBANSP)

Besc_context <- Besc_context %>%
  mutate(Besc_over_Bloss=Besc/Bloss_WKBANSP)

Besc_context <- Besc_context %>%
  mutate(Besc_over_WKBANSP_Blim=Besc/Blim_sigma020)

print(Besc_context,n=Inf)

# ============================================================
# S0 — DETERMINISTIC FORECAST
# ============================================================

diagnostic_S0 <- tibble(
  Besc=Besc_grid,
  scenario="S0",
  CV=0,
  SSB_required=Besc_grid
)

diagnostic_S0 <- diagnostic_S0 %>%
  mutate(SSB_required_p05=SSB_required)

diagnostic_S0 <- diagnostic_S0 %>%
  mutate(SSB_required_p95=SSB_required)

# ============================================================
# S1 — CURRENT ASSESSMENT UNCERTAINTY
# ============================================================

diagnostic_S1 <- tibble(
  Besc=Besc_grid,
  scenario="S1",
  CV=CV_S1
)

diagnostic_S1 <- diagnostic_S1 %>%
  mutate(SSB_required=map_dbl(Besc,~get_SSB_required(.x,CV_S1,alpha)))

diagnostic_S1 <- diagnostic_S1 %>%
  mutate(SSB_required_p05=SSB_required)

diagnostic_S1 <- diagnostic_S1 %>%
  mutate(SSB_required_p95=SSB_required)

# ============================================================
# S2 — CONTEMPORARY BOOTSTRAP UNCERTAINTY
#
# Each Besc is evaluated against the complete empirical
# distribution of forecast CV obtained from the 100
# bootstrap-conditioned assessments.
# ============================================================

CV_S2_table <- tibble(
  bootstrap=seq_along(CV_S2),
  CV=CV_S2
)

diagnostic_S2_raw <- crossing(
  Besc=Besc_grid,
  bootstrap=seq_along(CV_S2)
)

diagnostic_S2_raw <- diagnostic_S2_raw %>%
  left_join(CV_S2_table,by="bootstrap")

diagnostic_S2_raw <- diagnostic_S2_raw %>%
  mutate(SSB_required=map2_dbl(Besc,CV,~get_SSB_required(.x,.y,alpha)))

# ============================================================
# SUMMARISE S2
# ============================================================

diagnostic_S2 <- diagnostic_S2_raw %>%
  group_by(Besc) %>%
  summarise(
    scenario="S2",
    CV=median(CV),
    SSB_required_p05=quantile(SSB_required,.05),
    SSB_required_p95=quantile(SSB_required,.95),
    SSB_required=median(SSB_required),
    .groups="drop"
  )

# ============================================================
# COMBINE FORECAST UNCERTAINTY SCENARIOS
# ============================================================

diagnostic <- bind_rows(diagnostic_S0,diagnostic_S1,diagnostic_S2)

diagnostic <- diagnostic %>%
  mutate(scenario=factor(scenario,
                         levels=c("S0","S1","S2"),
                         labels=c("S0: deterministic",
                                  "S1: current assessment",
                                  "S2: contemporary uncertainty")))

# ============================================================
# CANDIDATE BESC DIAGNOSTIC
# ============================================================

candidate_diagnostic <- diagnostic %>%
  filter(Besc %in% Besc_candidates)

candidate_diagnostic <- candidate_diagnostic %>%
  left_join(Besc_context,by="Besc")

candidate_diagnostic <- candidate_diagnostic %>%
  arrange(Besc,scenario)

print(candidate_diagnostic,n=Inf)

# ============================================================
# UNCERTAINTY-INDUCED BUFFER
# ============================================================

candidate_buffer <- candidate_diagnostic %>%
  mutate(absolute_buffer=SSB_required-Besc)

candidate_buffer <- candidate_buffer %>%
  mutate(relative_buffer=SSB_required/Besc)

candidate_buffer <- candidate_buffer %>%
  mutate(percent_buffer=100*(relative_buffer-1))

print(candidate_buffer,n=Inf)

# ============================================================
# REQUIRED SSB RELATIVE TO CURRENT REFERENCE POINTS
# ============================================================

candidate_relative <- candidate_diagnostic %>%
  mutate(SSB_required_over_Blim=SSB_required/Blim)

candidate_relative <- candidate_relative %>%
  mutate(SSB_required_over_Bpa=SSB_required/Bpa)

print(candidate_relative,n=Inf)

# ============================================================
# UNCERTAINTY MULTIPLIER
# For a fixed CV:
# SSB_required / Besc =
# 1 / (1 + z_alpha * CV)
# ============================================================

uncertainty_multiplier <- forecast_CV_summary %>%
  mutate(denominator=1+z_alpha*CV_median)

uncertainty_multiplier <- uncertainty_multiplier %>%
  mutate(SSB_multiplier=if_else(denominator>0,1/denominator,Inf))

print(uncertainty_multiplier)

# ============================================================
# REPORTING TABLE
# ============================================================

candidate_table <- candidate_diagnostic %>%
  select(Besc,Besc_over_Blim,Besc_over_Bpa,Besc_over_B0,Besc_over_Bloss,scenario,CV,SSB_required,SSB_required_p05,SSB_required_p95)

candidate_table <- candidate_table %>%
  pivot_wider(names_from=scenario,values_from=c(CV,SSB_required,SSB_required_p05,SSB_required_p95))

print(candidate_table,n=Inf)

# ============================================================
# CHECKS
# ============================================================

stopifnot(all(is.finite(diagnostic_S0$SSB_required)))
stopifnot(all(is.finite(diagnostic_S1$SSB_required)))
stopifnot(all(diagnostic_S0$SSB_required==diagnostic_S0$Besc))
stopifnot(all(diagnostic_S1$SSB_required>=diagnostic_S1$Besc))
stopifnot(all(diagnostic_S2$SSB_required>=diagnostic_S2$Besc))
stopifnot(n_distinct(Besc_context$Besc)==length(Besc_candidates))
stopifnot(all(Besc_candidates %in% diagnostic$Besc))
stopifnot(Blim_sigma020<Bpa_WKBANSP)
stopifnot(n_distinct(diagnostic_S2_raw$CV)==length(unique(CV_S2)))

stopifnot(all(diagnostic_S2$SSB_required_p05<=diagnostic_S2$SSB_required))

stopifnot(all(diagnostic_S2$SSB_required_p95>=diagnostic_S2$SSB_required))

stopifnot(any(diagnostic_S2$SSB_required_p05<diagnostic_S2$SSB_required_p95))

# ============================================================
# SAVE
# ============================================================

settings <- list(Blim=Blim,Bpa=Bpa,B0_WKBANSP=B0_WKBANSP,Bloss_WKBANSP=Bloss_WKBANSP,alpha=alpha,z_alpha=z_alpha,Besc_candidates=Besc_candidates,Besc_grid=Besc_grid)
outputs <- list(settings=settings,reference_points=reference_points,forecast_CV_summary=forecast_CV_summary,CV_S1=CV_S1,CV_S2=CV_S2,Besc_scale=Besc_scale,Besc_context=Besc_context,diagnostic=diagnostic,diagnostic_S2_raw=diagnostic_S2_raw,candidate_diagnostic=candidate_diagnostic,candidate_table=candidate_table,candidate_buffer=candidate_buffer,candidate_relative=candidate_relative,uncertainty_multiplier=uncertainty_multiplier)

saveRDS(outputs,file.path(out_dir,"BESC_candidate_range_diagnostic.rds"))

write.csv(reference_points,file.path(out_dir,"BESC_reference_point_context.csv"),row.names=FALSE)
write.csv(forecast_CV_summary,file.path(out_dir,"BESC_forecast_CV_summary.csv"),row.names=FALSE)
write.csv(Besc_context,file.path(out_dir,"BESC_candidate_biological_scale.csv"),row.names=FALSE)
write.csv(diagnostic,file.path(out_dir,"BESC_required_SSB_diagnostic.csv"),row.names=FALSE)
write.csv(candidate_diagnostic,file.path(out_dir,"BESC_candidate_diagnostic.csv"),row.names=FALSE)
write.csv(candidate_table,file.path(out_dir,"BESC_candidate_summary_table.csv"),row.names=FALSE)
write.csv(candidate_buffer,file.path(out_dir,"BESC_candidate_uncertainty_buffer.csv"),row.names=FALSE)
write.csv(candidate_relative,file.path(out_dir,"BESC_candidate_relative_reference_points.csv"),row.names=FALSE)

# ============================================================
# FIGURE 1
# STOCK-SPECIFIC REFERENCE-POINT CONTEXT
# ============================================================

reference_plot <- reference_points %>%
  mutate(reference=factor(reference,levels=reference[order(value)]))

p1 <- ggplot(reference_plot,aes(value,reference)) +
  geom_point(size=3) +
  geom_vline(xintercept=Blim,linetype=2) +
  geom_vline(xintercept=Bpa,linetype=2) +
  theme_bw() +
  labs(x="Spawning stock biomass (t)",y=NULL,title="Stock-specific biomass reference-point context",subtitle="Alternative reference-point values evaluated for ane.27.9a South")

ggsave(file.path(fig_dir,"BESC_reference_point_context.png"),p1,width=8,height=5.5,dpi=300)

# ============================================================
# FIGURE 2
# CANDIDATE BESC RELATIVE TO CURRENT BLIM AND BPA
# ============================================================

Besc_scale_plot <- Besc_scale %>%
  select(Besc,Besc_over_Blim,Besc_over_Bpa)

Besc_scale_plot <- Besc_scale_plot %>%
  pivot_longer(cols=c(Besc_over_Blim,Besc_over_Bpa),names_to="reference",values_to="ratio")

Besc_scale_plot <- Besc_scale_plot %>%
  mutate(reference=recode(reference,Besc_over_Blim="Besc / Blim",Besc_over_Bpa="Besc / Bpa"))

p2 <- ggplot(Besc_scale_plot,aes(Besc,ratio)) +
  geom_hline(yintercept=1,linetype=2) +
  geom_line() +
  geom_point(size=2.5) +
  facet_wrap(~reference,nrow=1) +
  theme_bw() +
  labs(x="Candidate escapement biomass, Besc (t)",y="Ratio",title="Candidate Besc values relative to current biological reference points")

ggsave(file.path(fig_dir,"BESC_relative_to_reference_points.png"),p2,width=9,height=4.5,dpi=300)

# ============================================================
# FIGURE 3
# EXPECTED SSB REQUIRED ACROSS THE DIAGNOSTIC RANGE
# ============================================================

S2_ribbon <- diagnostic %>%
  filter(scenario=="S2: contemporary uncertainty")

p3 <- ggplot(diagnostic,aes(Besc,SSB_required,linetype=scenario)) +
  geom_ribbon(data=S2_ribbon,aes(x=Besc,ymin=SSB_required_p05,ymax=SSB_required_p95),inherit.aes=FALSE,alpha=.2) +
  geom_line(linewidth=.9) +
  geom_vline(xintercept=Blim,linetype=3) +
  geom_vline(xintercept=Bpa,linetype=2) +
  geom_abline(intercept=0,slope=1,linetype=3) +
  theme_bw() +
  labs(x="Escapement biomass, Besc (t)",y="Expected SSB required (t)",
       linetype="Forecast uncertainty",
       title="Expected SSB required to satisfy the escapement probability criterion",
       subtitle=paste0("Criterion: P(SSBforecast < Besc) <= ",alpha))

ggsave(file.path(fig_dir,"BESC_required_SSB_by_uncertainty.png"),p3,width=8,height=6,dpi=300)

# ============================================================
# FIGURE 4
# CANDIDATE BESC VALUES ONLY
# ============================================================

p4 <- ggplot(candidate_diagnostic,aes(factor(Besc),SSB_required,group=scenario,linetype=scenario)) +
  geom_line(linewidth=.8) +
  geom_point(size=2.5) +
  geom_errorbar(aes(ymin=SSB_required_p05,ymax=SSB_required_p95),width=.08) +
  theme_bw() +
  labs(x="Candidate Besc (t)",y="Expected SSB required (t)",linetype="Forecast uncertainty",title="Operational implications of candidate Besc values")

ggsave(file.path(fig_dir,"BESC_candidate_required_SSB.png"),p4,width=8,height=5.5,dpi=300)

# ============================================================
# FIGURE 5
# UNCERTAINTY-INDUCED BUFFER
# ============================================================

p5 <- ggplot(candidate_buffer,aes(factor(Besc),percent_buffer,group=scenario,linetype=scenario)) +
  geom_line(linewidth=.8) +
  geom_point(size=2.5) +
  theme_bw() +
  labs(x="Candidate Besc (t)",y="Additional expected SSB required (%)",linetype="Forecast uncertainty",title="Forecast-uncertainty buffer associated with the escapement criterion")

ggsave(file.path(fig_dir,"BESC_uncertainty_buffer.png"),p5,width=8,height=5.5,dpi=300)

# ============================================================
# CONSOLE SUMMARY
# ============================================================

cat("\n============================================================\n")
cat("BESC CANDIDATE RANGE DIAGNOSTIC COMPLETED\n")
cat("============================================================\n")
cat("\nCurrent MSE reference points:\n")
cat("Blim:",Blim,"t\n")
cat("Bpa:",Bpa,"t\n")
cat("\nWKBANSP reference-point context:\n")
cat("B0:",B0_WKBANSP,"t\n")
cat("Bloss / Bpa:",Bloss_WKBANSP,"t\n")
cat("0.2 B0:",Blim_02B0,"t\n")
cat("Blim sigmaB=0.30:",Blim_sigma030,"t\n")
cat("Blim sigmaB=0.20:",Blim_sigma020,"t\n")
cat("Blim sigmaB=0.10:",Blim_sigma010,"t\n")
cat("\nCandidate Besc:",paste(Besc_candidates,collapse=", "),"t\n")
cat("Diagnostic range:",min(Besc_grid),"-",max(Besc_grid),"t\n")
cat("Alpha:",alpha,"\n")
cat("\nForecast uncertainty:\n")
cat("S0 CV: 0\n")
cat("S1 CV:",round(CV_S1,4),"\n")
cat("S2 median CV:",round(median(CV_S2),4),"\n")
cat("S2 P05-P95 CV:",round(quantile(CV_S2,.05),4),"-",round(quantile(CV_S2,.95),4),"\n")
cat("\nCandidate Besc relative to reference points:\n")

print(Besc_context,n=Inf)

cat("\nExpected SSB required by candidate and scenario:\n")

print(candidate_diagnostic %>% select(Besc,scenario,CV,SSB_required,SSB_required_p05,SSB_required_p95),n=Inf)

cat("\nOutputs:",out_dir,"\n")

cat("============================================================\n")

