# ============================================================
# 21d_DIAGNOSE_REFINED_MP_DYNAMICS.R
# Closed-loop dynamic diagnostics for candidate Fcap-Besc MPs
#
# Stock / analysis:
#   European anchovy ane.27.9aS, Gulf of Cádiz
#   Shortcut MSE implemented in FLBEIA + FLasher
#
# Refined-grid adaptation:
#   This script diagnoses the definitive 28-MP refined grid.
#   refined_scenario_number is mapped internally to scenario_number
#   for downstream diagnostic code only; simulation directories are
#   still located by scenario_id. Existing FLBEIA outputs are not modified.
#
# Role in the workflow:
#
#   20_RUN_MP_SCENARIO_PROBABILISTIC.R
#                     |
#                     v
#   21_CHECK_MP_SCENARIO_PROBABILISTIC.R / 21c_CHECK_REFINED_NEW_MPS.R
#                     |
#                     v
#   21d_DIAGNOSE_REFINED_MP_DYNAMICS.R
#                     |
#                     v
#   22_EVALUATE_CANDIDATE_MPS.R
#
# Purpose:
#   Diagnose the biological and fishery dynamics generated by
#   the complete closed-loop MSE before formal MP performance
#   evaluation.
#
#   The script examines:
#
#     - recruitment in Q3;
#     - SSB in Q2;
#     - annual realised catch;
#     - TAC advice;
#     - F advice;
#     - SSB crossings below Bpa and Blim;
#     - HCR response around low-stock states;
#     - closures and reopening;
#     - minimum SSB and associated management response;
#     - extreme values of SSB, recruitment, TAC, catch and Fadv.
#
#   Diagnostics are produced for all 28 refined candidate MPs and for
#   all 1000 trajectories per MP over 2025-2054.
#
# Inputs:
#   data/mse/scenarios/refined/candidate_MP_grid_refined.csv
#
#   data/mse/MP_runs/<scenario_id>/
#     block_XX.rds
#     block_XX_map.csv
#
# Outputs:
#   outputs/mse/diagnostics_refined/
#     21d_MP_dynamic_summary.csv
#     21d_MP_annual_diagnostics.csv
#     21d_MP_trajectory_diagnostics.csv
#     21d_MP_minimum_SSB_events.csv
#     21d_MP_Blim_crossing_events.csv
#     21d_MP_closure_events.csv
#     21d_MP_reopening_events.csv
#     21d_MP_extreme_trajectories.csv
#     21d_MP_dynamic_diagnostics.rds
#
# Working Document outputs:
#
#   Tables:
#     21d_WD_Table1_dynamic_summary.csv
#     21d_WD_Table2_annual_extremes.csv
#     21d_WD_Table3_extreme_trajectories.csv
#
#   Figures:
#     21d_WD_Figure1_recruitment_history_projection.png
#     21d_WD_Figure2_SSB_history_projection.png
#     21d_WD_Figure3_catch_history_projection.png
#     21d_WD_Figure4_TAC_history_projection.png
#     21d_WD_Figure5_Fadv_history_projection.png
#
# Important:
#   This is a diagnostic script.
#
#   It DOES NOT:
#     - rerun FLBEIA;
#     - modify the operating model;
#     - modify the management procedure;
#     - rank candidate MPs;
#     - select a preferred MP;
#     - define additional performance criteria;
#     - replace the performance evaluation in script 22.
#
#   Blim and Bpa crossings, closures, reopening and extreme
#   trajectories are diagnostic outputs and are not used here
#   as automatic acceptance or rejection criteria.
# ============================================================


# ============================================================
# 0. CLEAN WORKSPACE AND LOAD PACKAGES
# ============================================================

rm(list=ls())

library(FLCore)
library(FLBEIA)
library(dplyr)
library(tidyr)
library(purrr)
library(here)
library(ggplot2)


# ============================================================
# 1. DIRECTORIES AND SETTINGS ----
# ============================================================

scenario_file <- here("data", "mse", "scenarios", "refined", "candidate_MP_grid_refined.csv")
scenario_root <- here("data","mse","MP_runs")
diagnostic_dir <- here("outputs", "mse", "diagnostics_refined")
figure_dir <- file.path(diagnostic_dir,"figures")

dir.create(diagnostic_dir,recursive=TRUE,showWarnings=FALSE)
dir.create(figure_dir,recursive=TRUE,showWarnings=FALSE)

block_ids <- 1:10

expected_blocks <- 10
expected_block_size <- 100
expected_trajectories <- 1000
expected_OMs <- 100
expected_replicates <- 10

tol_F <- 1e-8
tol_TAC <- 1e-8

test_mode <- FALSE
test_scenarios <- 1:2

historical_years <- 1989:2024
transition_year <- 2024.5


# ============================================================
# 2. LOAD CANDIDATE MP GRID ----
# ============================================================

stopifnot(file.exists(scenario_file))

scenario_grid <- read.csv(scenario_file,stringsAsFactors=FALSE)

required_scenario_cols <- c(
  "refined_scenario_number",
  "scenario_id",
  "Fcap",
  "Besc",
  "Blim",
  "Bpa",
  "first_projection_year",
  "last_projection_year")

stopifnot(all(required_scenario_cols %in% names(scenario_grid)))
stopifnot(nrow(scenario_grid) == 28)
stopifnot(n_distinct(scenario_grid$refined_scenario_number) == 28)
stopifnot(n_distinct(scenario_grid$scenario_id) == 28)

scenario_grid <- scenario_grid %>%
  mutate(scenario_number = refined_scenario_number) %>%
  arrange(scenario_number)

if(test_mode){scenario_grid <- scenario_grid %>%filter(scenario_number %in% test_scenarios)}

cat("\nCandidate MPs to diagnose:",nrow(scenario_grid),"\n")


# ============================================================
# 3. HELPER FUNCTIONS ----
# ============================================================

add_global_map <- function(dat,map_b){
  
  out <- dat %>%mutate(iter_local=as.integer(as.character(iter))) %>%
    left_join(map_b %>%select(iter_local,iter1000,om,replicate),by="iter_local")
  
  stopifnot(!anyNA(out$iter1000))
  stopifnot(!anyNA(out$om))
  stopifnot(!anyNA(out$replicate))
  
  out
}


standardise_dynamic <- function(x,map_b,proj_years){
  
  out <- as.data.frame(x) %>%
    rename(value=data) %>%
    mutate(year=as.integer(as.character(year))) %>%
    add_global_map(map_b) %>%
    filter(year %in% proj_years) %>%
    transmute(year,iter1000,om,replicate,value)
  
  out
}


standardise_series <- function(x,map_b,years){
  
  out <- as.data.frame(x) %>%
    rename(value=data) %>%
    mutate(year=as.integer(as.character(year))) %>%
    add_global_map(map_b) %>%
    filter(year %in% years) %>%
    transmute(year,iter1000,om,replicate,value)
  
  out
}


# ============================================================
# 4. DIAGNOSE ONE CANDIDATE MP ----
# ============================================================

diagnose_candidate_MP <- function(scenario_row){
  
  scenario_number <- scenario_row$scenario_number[[1]]
  scenario_id <- scenario_row$scenario_id[[1]]
  Fcap <- scenario_row$Fcap[[1]]
  Besc <- scenario_row$Besc[[1]]
  Blim <- scenario_row$Blim[[1]]
  Bpa <- scenario_row$Bpa[[1]]
  first_proj <- scenario_row$first_projection_year[[1]]
  last_proj <- scenario_row$last_projection_year[[1]]
  proj_years <- first_proj:last_proj
  
  cat("\n============================================================\n")
  cat("SCENARIO:",scenario_number,"\n")
  cat("ID:",scenario_id,"\n")
  cat("Fcap:",Fcap,"| Besc:",Besc,"\n")
  cat("============================================================\n")
  
  
  # ==========================================================
  # 4.1 INPUT FILES
  # ==========================================================
  
  mp_dir <- file.path(scenario_root,scenario_id)
  mp_files <- file.path(mp_dir,sprintf("block_%02d.rds",block_ids))
  map_files <- file.path(mp_dir,sprintf("block_%02d_map.csv",block_ids))
  
  if(!dir.exists(mp_dir)){stop("Scenario directory not found: ",mp_dir)}
  if(!all(file.exists(mp_files))){stop("Missing RDS blocks for scenario ",scenario_number)}
  if(!all(file.exists(map_files))){stop("Missing map files for scenario ",scenario_number)}
  
  # ==========================================================
  # 4.2 VALIDATE COMPLETE ITERATION MAP
  # ==========================================================
  
  iteration_maps <- map_dfr(
    block_ids,
    ~read.csv(map_files[.x],stringsAsFactors=FALSE) %>%
      mutate(block=.x)
  )
  
  stopifnot(length(block_ids)==expected_blocks)
  stopifnot(nrow(iteration_maps)==expected_trajectories)
  stopifnot(n_distinct(iteration_maps$iter1000)==expected_trajectories)
  stopifnot(n_distinct(iteration_maps$om)==expected_OMs)
  stopifnot(all(table(iteration_maps$om)==expected_replicates))
  stopifnot(all(sort(unique(iteration_maps$replicate))==1:expected_replicates))
  stopifnot(!anyDuplicated(iteration_maps[,c("om","replicate")]))
  
  
  # ==========================================================
  # 4.3 EXTRACT ONE BLOCK
  # ==========================================================
  
  extract_MP_block <- function(block_id){
    
    OM_b <- readRDS(mp_files[block_id])
    map_b <- read.csv(map_files[block_id],stringsAsFactors=FALSE)
    
    stopifnot(nrow(map_b)==expected_block_size)
    
    biol <- OM_b$biols$ANE
    cobj <- OM_b$fleets$SEINE@metiers$ALL@catches$ANE
    
    R_b <- standardise_dynamic(biol@n["0",,,"3",,],map_b,proj_years)
    Mat <- predict(biol@mat)
    SSB_q2 <- quantSums(biol@n[,,,"2",,] *biol@wt[,,,"2",,] *Mat[,,,"2",,])
    B_b <- standardise_dynamic(SSB_q2,map_b,proj_years)
    C_ann <- seasonSums(quantSums(cobj@landings))
    C_b <- standardise_dynamic(C_ann,map_b,proj_years)
    TAC_b <- standardise_dynamic(OM_b$advice$TAC["ANE",,,,,],map_b,proj_years)
    Fadv_b <- standardise_dynamic(OM_b$advice$Fadv["ANE",,,,,],map_b,proj_years)
    R_hist_b <- standardise_series(biol@n["0",,,"3",,],map_b,historical_years)
    SSB_hist_q2 <- quantSums(biol@n[,,,"2",,] *biol@wt[,,,"2",,] *Mat[,,,"2",,])
    B_hist_b <- standardise_series(SSB_hist_q2,map_b,historical_years)
    C_hist_ann <- seasonSums(quantSums(cobj@landings))
    C_hist_b <- standardise_series(C_hist_ann,map_b,historical_years)
    TAC_hist_b <- standardise_series(OM_b$advice$TAC["ANE",,,,,],map_b,historical_years)
    Fadv_hist_b <- standardise_series(OM_b$advice$Fadv["ANE",,,,,],map_b,historical_years)
    
    list(
      R=R_b,
      SSB=B_b,
      Catch=C_b,
      TAC=TAC_b,
      Fadv=Fadv_b,
      R_hist=R_hist_b,
      SSB_hist=B_hist_b,
      Catch_hist=C_hist_b,
      TAC_hist=TAC_hist_b,
      Fadv_hist=Fadv_hist_b)
  }
  
  
  # ==========================================================
  # 4.4 EXTRACT COMPLETE CLOSED-LOOP ENSEMBLE
  # ==========================================================
  
  MP_blocks <- map(block_ids,extract_MP_block)
  
  R_MP <- map_dfr(MP_blocks,"R")
  B_MP <- map_dfr(MP_blocks,"SSB")
  C_MP <- map_dfr(MP_blocks,"Catch")
  TAC_MP <- map_dfr(MP_blocks,"TAC")
  Fadv_MP <- map_dfr(MP_blocks,"Fadv")
  R_hist_MP <- map_dfr(MP_blocks,"R_hist")
  B_hist_MP <- map_dfr(MP_blocks,"SSB_hist")
  C_hist_MP <- map_dfr(MP_blocks,"Catch_hist")
  TAC_hist_MP <- map_dfr(MP_blocks,"TAC_hist")
  Fadv_hist_MP <- map_dfr(MP_blocks,"Fadv_hist")
  
  rm(MP_blocks)
  
  gc(verbose=FALSE)
  
  expected_rows <- expected_trajectories*length(proj_years)
  
  stopifnot(nrow(R_MP)==expected_rows)
  stopifnot(nrow(B_MP)==expected_rows)
  stopifnot(nrow(C_MP)==expected_rows)
  stopifnot(nrow(TAC_MP)==expected_rows)
  stopifnot(nrow(Fadv_MP)==expected_rows)
  
  
  # ==========================================================
  # 4.5 BUILD COMPLETE YEAR × TRAJECTORY DATASET
  # ==========================================================
  
  dynamics <- B_MP %>%
    rename(SSB=value) %>%
    left_join(R_MP %>%rename(R=value),by=c("year","iter1000","om","replicate")) %>%
    left_join(C_MP %>%rename(Catch=value),by=c("year","iter1000","om","replicate")) %>%
    left_join(TAC_MP %>%rename(TAC=value),by=c("year","iter1000","om","replicate")) %>%
    left_join(
      Fadv_MP %>%
        rename(Fadv=value),
      by=c("year","iter1000","om","replicate")
    ) %>%
    arrange(iter1000,year)
  
  stopifnot(nrow(dynamics)==expected_rows)
  
  stopifnot(!anyNA(dynamics$SSB))
  stopifnot(!anyNA(dynamics$R))
  stopifnot(!anyNA(dynamics$Catch))
  stopifnot(!anyNA(dynamics$TAC))
  stopifnot(!anyNA(dynamics$Fadv))
  
  stopifnot(all(is.finite(dynamics$SSB)))
  stopifnot(all(is.finite(dynamics$R)))
  stopifnot(all(is.finite(dynamics$Catch)))
  stopifnot(all(is.finite(dynamics$TAC)))
  stopifnot(all(is.finite(dynamics$Fadv)))
  
  stopifnot(all(dynamics$SSB>=0))
  stopifnot(all(dynamics$R>=0))
  stopifnot(all(dynamics$Catch>=0))
  stopifnot(all(dynamics$TAC>=0))
  stopifnot(all(dynamics$Fadv>=0))
  stopifnot(all(dynamics$Fadv<=Fcap+tol_F))
  
  
  # ==========================================================
  # 4.6 DEFINE DIAGNOSTIC STATES
  # ==========================================================
  
  dynamics <- dynamics %>%
    group_by(iter1000,om,replicate) %>%
    arrange(year,.by_group=TRUE) %>%
    mutate(
      below_Blim=SSB<Blim,
      below_Bpa=SSB<Bpa,
      closed=Fadv<=tol_F,
      TAC_zero=TAC<=tol_TAC,
      previous_closed=lag(closed,default=FALSE),
      closure_start=closed & !previous_closed,
      reopening=!closed & previous_closed
    ) %>%
    ungroup()
  
  
  # ==========================================================
  # 4.7 ANNUAL CLOSED-LOOP DIAGNOSTICS
  # ==========================================================
  
  annual_summary <- dynamics %>%
    group_by(year) %>%
    summarise(
      SSB_median=median(SSB),
      SSB_p05=quantile(SSB,0.05),
      SSB_p95=quantile(SSB,0.95),
      SSB_min=min(SSB),
      R_median=median(R),
      R_p05=quantile(R,0.05),
      R_p95=quantile(R,0.95),
      Catch_median=median(Catch),
      Catch_p05=quantile(Catch,0.05),
      Catch_p95=quantile(Catch,0.95),
      TAC_median=median(TAC),
      TAC_p05=quantile(TAC,0.05),
      TAC_p95=quantile(TAC,0.95),
      Fadv_median=median(Fadv),
      Fadv_p05=quantile(Fadv,0.05),
      Fadv_p95=quantile(Fadv,0.95),
      P_Blim=mean(below_Blim),
      P_Bpa=mean(below_Bpa),
      P_closed=mean(closed),
      .groups="drop"
    ) %>%
    mutate(
      scenario_number=scenario_number,
      scenario_id=scenario_id,
      Fcap=Fcap,
      Besc=Besc,
      Blim=Blim,
      Bpa=Bpa,
      .before=1
    )
  
  # ==========================================================
  # HCR OPERATING-STATE DIAGNOSTIC
  # ==========================================================
  #
  # Each year × trajectory is classified according to the
  # management advice produced by the HCR.
  #
  # closed:
  #   Fadv approximately zero.
  #
  # restricted:
  #   Fadv is positive but lower than Fcap.
  #
  # at_Fcap:
  #   Fadv is approximately equal to Fcap.
  #
  # This is a diagnostic classification and is not used as an
  # MP acceptance or selection criterion.
  # ==========================================================
  
  HCR_state_summary <- dynamics %>%
    mutate(
      HCR_state=case_when(
        Fadv<=tol_F ~ "closed",
        abs(Fadv-Fcap)<=tol_F ~ "at_Fcap",
        Fadv>tol_F & Fadv<Fcap-tol_F ~ "restricted",
        TRUE ~ "other")) %>%
    count(HCR_state,name="n") %>%
    complete(HCR_state=c("closed","restricted","at_Fcap","other"),fill=list(n=0)) %>%
    mutate(
      proportion=n/sum(n),
      scenario_number=scenario_number,
      scenario_id=scenario_id,
      Fcap=Fcap,
      Besc=Besc,
      .before=1)
  
  HCR_state_annual <- dynamics %>%
    mutate(
      HCR_state=case_when(
        Fadv<=tol_F ~ "closed",
        abs(Fadv-Fcap)<=tol_F ~ "at_Fcap",
        Fadv>tol_F & Fadv<Fcap-tol_F ~ "restricted",
        TRUE ~ "other")) %>%
    count(year,HCR_state,name="n") %>%
    complete(
      year=proj_years,
      HCR_state=c("closed","restricted","at_Fcap","other"),
      fill=list(n=0)) %>%
    group_by(year) %>%
    mutate(proportion=n/sum(n)) %>%
    ungroup() %>%
    mutate(
      scenario_number=scenario_number,
      scenario_id=scenario_id,
      Fcap=Fcap,
      Besc=Besc,
      .before=1)
  
  # ==========================================================
  # CLOSURE PERSISTENCE AND SWITCHING DIAGNOSTIC
  # ==========================================================
  #
  # Quantifies how persistent closures are and how frequently
  # trajectories switch between open and closed states.
  #
  # This is a diagnostic description of HCR behaviour and is
  # not used as an MP acceptance or selection criterion.
  # ==========================================================
  
  closure_runs <- dynamics %>%
    arrange(iter1000,year) %>%
    group_by(iter1000,om,replicate) %>%
    mutate(
      closure_run_id=cumsum(closed!=lag(closed,default=first(closed)))
    ) %>%
    filter(closed) %>%
    group_by(iter1000,om,replicate,closure_run_id) %>%
    summarise(
      start_year=min(year),
      end_year=max(year),
      duration=end_year-start_year+1,
      .groups="drop"
    )
  
  closure_persistence_summary <- tibble(
    scenario_number=scenario_number,
    scenario_id=scenario_id,
    Fcap=Fcap,
    Besc=Besc,
    n_closure_runs=nrow(closure_runs),
    mean_closure_duration=if(nrow(closure_runs)>0) mean(closure_runs$duration) else 0,
    median_closure_duration=if(nrow(closure_runs)>0) median(closure_runs$duration) else 0,
    p95_closure_duration=if(nrow(closure_runs)>0) as.numeric(quantile(closure_runs$duration,0.95)) else 0,
    max_closure_duration=if(nrow(closure_runs)>0) max(closure_runs$duration) else 0
  )
  
  switching_summary <- dynamics %>%
    arrange(iter1000,year) %>%
    group_by(iter1000,om,replicate) %>%
    summarise(
      n_closure_events=sum(closure_start),
      n_reopening_events=sum(reopening),
      n_switches=n_closure_events+n_reopening_events,
      .groups="drop"
    ) %>%
    summarise(
      mean_closure_events=mean(n_closure_events),
      median_closure_events=median(n_closure_events),
      max_closure_events=max(n_closure_events),
      mean_reopening_events=mean(n_reopening_events),
      median_reopening_events=median(n_reopening_events),
      max_reopening_events=max(n_reopening_events),
      mean_switches=mean(n_switches),
      median_switches=median(n_switches),
      max_switches=max(n_switches)
    ) %>%
    mutate(
      scenario_number=scenario_number,
      scenario_id=scenario_id,
      Fcap=Fcap,
      Besc=Besc,
      .before=1
    )
  
  # ==========================================================
  # 4.8 TRAJECTORY-LEVEL DIAGNOSTICS
  # ==========================================================
  
  trajectory_summary <- dynamics %>%
    group_by(iter1000,om,replicate) %>%
    summarise(
      min_SSB=min(SSB),
      year_min_SSB=year[which.min(SSB)],
      mean_SSB=mean(SSB),
      median_SSB=median(SSB),
      min_R=min(R),
      max_R=max(R),
      mean_Catch=mean(Catch),
      max_Catch=max(Catch),
      mean_TAC=mean(TAC),
      max_TAC=max(TAC),
      mean_Fadv=mean(Fadv),
      max_Fadv=max(Fadv),
      ever_below_Blim=any(below_Blim),
      ever_below_Bpa=any(below_Bpa),
      n_years_below_Blim=sum(below_Blim),
      n_years_below_Bpa=sum(below_Bpa),
      ever_closed=any(closed),
      n_years_closed=sum(closed),
      n_closure_events=sum(closure_start),
      n_reopening_events=sum(reopening),
      .groups="drop"
    ) %>%
    mutate(
      scenario_number=scenario_number,
      scenario_id=scenario_id,
      Fcap=Fcap,
      Besc=Besc,
      .before=1
    )
  
  
  # ==========================================================
  # 4.9 MINIMUM-SSB EVENTS
  # ==========================================================
  #
  # One row is retained per trajectory at the year of minimum
  # SSB. This allows the management response associated with
  # the lowest stock state to be inspected directly.
  # ==========================================================
  
  minimum_SSB_events <- dynamics %>%
    group_by(iter1000,om,replicate) %>%
    slice_min(order_by=SSB,n=1, with_ties=FALSE) %>%
    ungroup() %>%
    mutate(
      scenario_number=scenario_number,
      scenario_id=scenario_id,
      Fcap=Fcap,
      Besc=Besc,
      .before=1)
  
  
  # ==========================================================
  # 4.10 BLIM CROSSING EVENTS
  # ==========================================================
  
  Blim_crossing_events <- dynamics %>%
    group_by(iter1000,om,replicate) %>%
    arrange(year,.by_group=TRUE) %>%
    mutate(previous_below_Blim=lag(below_Blim,default=FALSE)) %>%
    filter(below_Blim & !previous_below_Blim) %>%
    ungroup() %>%
    mutate(
      scenario_number=scenario_number,
      scenario_id=scenario_id,
      Fcap=Fcap,
      Besc=Besc,
      .before=1)
  
  # ==========================================================
  # 4.11 CLOSURE EVENTS
  # ==========================================================
  
  closure_events <- dynamics %>%
    filter(closure_start) %>%
    mutate(
      scenario_number=scenario_number,
      scenario_id=scenario_id,
      Fcap=Fcap,
      Besc=Besc,
      .before=1)
  
  # ==========================================================
  # 4.12 REOPENING EVENTS
  # ==========================================================
  
  reopening_events <- dynamics %>%
    filter(reopening) %>%
    mutate(
      scenario_number=scenario_number,
      scenario_id=scenario_id,
      Fcap=Fcap,
      Besc=Besc,
      .before=1)
  
  # ==========================================================
  # 4.13 EXTREME TRAJECTORIES FOR LATER INSPECTION
  # ==========================================================
  #
  # These trajectories are retained as diagnostic cases.
  # Their identification does not imply failure of the MP.
  # ==========================================================
  
  extreme_trajectories <- bind_rows(
    trajectory_summary %>%
      arrange(min_SSB) %>%
      slice_head(n=10) %>%
      mutate(diagnostic_case="lowest_min_SSB"),
    trajectory_summary %>%
      arrange(desc(max_Fadv)) %>%
      slice_head(n=10) %>%
      mutate(diagnostic_case="highest_Fadv"),
    trajectory_summary %>%
      arrange(desc(max_TAC)) %>%
      slice_head(n=10) %>%
      mutate(diagnostic_case="highest_TAC"),
    trajectory_summary %>%
      arrange(desc(max_Catch)) %>%
      slice_head(n=10) %>%
      mutate(diagnostic_case="highest_Catch"),
    trajectory_summary %>%
      arrange(desc(n_years_closed)) %>%
      slice_head(n=10) %>%
      mutate(diagnostic_case="most_years_closed")) %>%
    distinct(scenario_number,iter1000,diagnostic_case,.keep_all=TRUE)
  
  
  # ==========================================================
  # 4.14 SCENARIO-LEVEL DYNAMIC SUMMARY
  # ==========================================================
  
  dynamic_summary <- trajectory_summary %>%
    summarise(
      scenario_number=first(scenario_number),
      scenario_id=first(scenario_id),
      Fcap=first(Fcap),
      Besc=first(Besc),
      n_trajectories=dplyr::n(),
      min_SSB=min(min_SSB),
      median_min_SSB=median(min_SSB),
      P_ever_Blim=mean(ever_below_Blim),
      P_ever_Bpa=mean(ever_below_Bpa),
      P_ever_closed=mean(ever_closed),
      mean_years_below_Blim=mean(n_years_below_Blim),
      mean_years_closed=mean(n_years_closed),
      max_years_closed=max(n_years_closed),
      total_closure_events=sum(n_closure_events),
      total_reopening_events=sum(n_reopening_events),
      max_Fadv=max(max_Fadv),
      max_TAC=max(max_TAC),
      max_Catch=max(max_Catch)
    )
  
  
  # ==========================================================
  # 4.15 HISTORICAL SERIES FOR WORKING DOCUMENT FIGURES
  # ==========================================================
  
  historical_summary <- list(
    R=R_hist_MP,
    SSB=B_hist_MP,
    Catch=C_hist_MP,
    TAC=TAC_hist_MP,
    Fadv=Fadv_hist_MP
  )
  
  # ==========================================================
  # 4.16 INTERNAL DIAGNOSTIC CHECKS
  # ==========================================================
  
  stopifnot(nrow(trajectory_summary)==expected_trajectories)
  stopifnot(nrow(minimum_SSB_events)==expected_trajectories)
  
  stopifnot(all(trajectory_summary$n_years_closed>=0))
  stopifnot(all(trajectory_summary$n_years_closed<=length(proj_years)))
  
  stopifnot(all(trajectory_summary$n_years_below_Blim>=0))
  stopifnot(all(trajectory_summary$n_years_below_Blim<=length(proj_years)))
  
  cat("Dynamic diagnostic completed\n")
  cat("Minimum SSB:",dynamic_summary$min_SSB,"t\n")
  cat("P ever below Blim:",dynamic_summary$P_ever_Blim,"\n")
  cat("P ever below Bpa:",dynamic_summary$P_ever_Bpa,"\n")
  cat("P ever closed:",dynamic_summary$P_ever_closed,"\n")
  cat("Closure events:",dynamic_summary$total_closure_events,"\n")
  cat("Reopening events:",dynamic_summary$total_reopening_events,"\n")
  
  
  # ==========================================================
  # 4.17 RETURN SCENARIO DIAGNOSTICS
  # ==========================================================
  
  list(
    summary=dynamic_summary,
    annual=annual_summary,
    trajectory=trajectory_summary,
    minimum_SSB=minimum_SSB_events,
    Blim_crossings=Blim_crossing_events,
    closures=closure_events,
    reopenings=reopening_events,
    extremes=extreme_trajectories,
    HCR_state=HCR_state_summary,
    HCR_state_annual=HCR_state_annual,
    closure_persistence=closure_persistence_summary,
    switching=switching_summary,
    historical=historical_summary
  )
}


# ============================================================
# 5. DIAGNOSE ALL CANDIDATE MPs ----
# ============================================================

candidate_diagnostics <- map(seq_len(nrow(scenario_grid)),
                             ~diagnose_candidate_MP(scenario_grid[.x,,drop=FALSE]))


# ============================================================
# 6. COMBINE DIAGNOSTIC OUTPUTS ----
# ============================================================

dynamic_summary <- map_dfr(candidate_diagnostics,"summary")
annual_diagnostics <- map_dfr(candidate_diagnostics,"annual")
trajectory_diagnostics <- map_dfr(candidate_diagnostics,"trajectory")
minimum_SSB_events <- map_dfr(candidate_diagnostics,"minimum_SSB")
Blim_crossing_events <- map_dfr(candidate_diagnostics,"Blim_crossings")
closure_events <- map_dfr(candidate_diagnostics,"closures")
reopening_events <- map_dfr(candidate_diagnostics,"reopenings")
extreme_trajectories <- map_dfr(candidate_diagnostics,"extremes")
HCR_state_diagnostics <- map_dfr(candidate_diagnostics,"HCR_state")
HCR_state_annual_diagnostics <- map_dfr(candidate_diagnostics,"HCR_state_annual")
closure_persistence_diagnostics <- map_dfr(candidate_diagnostics,"closure_persistence")
switching_diagnostics <- map_dfr(candidate_diagnostics,"switching")
historical_reference <- candidate_diagnostics[[1]]$historical

R_historical <- historical_reference$R
SSB_historical <- historical_reference$SSB
Catch_historical <- historical_reference$Catch
TAC_historical <- historical_reference$TAC
Fadv_historical <- historical_reference$Fadv


# ============================================================
# 7. GLOBAL STRUCTURAL CHECKS
# ============================================================

n_scenarios <- nrow(scenario_grid)

stopifnot(nrow(dynamic_summary)==n_scenarios)
stopifnot(n_distinct(dynamic_summary$scenario_number)==n_scenarios)
stopifnot(nrow(trajectory_diagnostics)==n_scenarios*expected_trajectories)
stopifnot(nrow(minimum_SSB_events)==n_scenarios*expected_trajectories)
stopifnot(all(dynamic_summary$n_trajectories==expected_trajectories))
stopifnot(all(dynamic_summary$min_SSB>=0))
stopifnot(all(dynamic_summary$max_Fadv<=dynamic_summary$Fcap+tol_F))

# ============================================================
# 8. HCR OPERATING-STATE DIAGNOSTIC
# ============================================================

table_HCR_state <- HCR_state_diagnostics %>%
  select(scenario_number,Fcap,Besc,HCR_state,proportion) %>%
  pivot_wider(names_from=HCR_state,values_from=proportion,values_fill=0) %>%
  arrange(Besc,Fcap)

table_closure_dynamics <- closure_persistence_diagnostics %>%
  left_join(
    switching_diagnostics,
    by=c("scenario_number","scenario_id","Fcap","Besc")
  ) %>%
  arrange(Besc,Fcap)

print(
  table_closure_dynamics,
  n=Inf
)

stopifnot(all(table_closure_dynamics$n_closure_runs>=0))

stopifnot(all(table_closure_dynamics$mean_closure_duration>=0))

cat("Closure persistence and switching diagnostics: PASS\n")


HCR_state_check <- table_HCR_state %>%
  mutate(total=closed+restricted+at_Fcap+other)

stopifnot(all(abs(HCR_state_check$total-1)<1e-10))
stopifnot(all(HCR_state_check$other==0))

cat("\nHCR OPERATING-STATE DIAGNOSTIC\n")

print(table_HCR_state,n=Inf)

cat("HCR operating-state classification: PASS\n")
# ============================================================
# 9. TABLES FOR THE WORKING DOCUMENT
# ============================================================
#
# These tables summarise the dynamic diagnostics already
# calculated above. They do not introduce additional
# performance criteria or MP-selection rules.
# ============================================================


# ------------------------------------------------------------
# WD Table 1 - Scenario-level dynamic summary
# ------------------------------------------------------------

table_WD_dynamic_summary <- dynamic_summary %>%
  select(
    scenario_number,
    Fcap,
    Besc,
    min_SSB,
    median_min_SSB,
    P_ever_Blim,
    P_ever_Bpa,
    P_ever_closed,
    mean_years_closed,
    max_years_closed,
    total_closure_events,
    total_reopening_events
  )


# ------------------------------------------------------------
# WD Table 2 - Annual diagnostic extremes
# ------------------------------------------------------------

table_WD_annual_extremes <- annual_diagnostics %>%
  group_by(scenario_number,Fcap,Besc) %>%
  summarise(
    max_P_Blim=max(P_Blim),
    year_max_P_Blim=year[which.max(P_Blim)],
    max_P_closed=max(P_closed),
    year_max_P_closed=year[which.max(P_closed)],
    min_annual_median_SSB=min(SSB_median),
    year_min_median_SSB=year[which.min(SSB_median)],
    .groups="drop")


# ------------------------------------------------------------
# WD Table 3 - Lowest-SSB trajectories
# ------------------------------------------------------------

table_WD_extreme_trajectories <- trajectory_diagnostics %>%
  group_by(scenario_number,Fcap,Besc) %>%
  slice_min(order_by=min_SSB,n=3,with_ties=FALSE) %>%
  ungroup() %>%
  select(
    scenario_number,
    Fcap,
    Besc,
    iter1000,
    om,
    replicate,
    min_SSB,
    year_min_SSB,
    n_years_below_Blim,
    n_years_closed,
    n_closure_events,
    n_reopening_events)


# ============================================================
# 10. PREPARE HISTORICAL-PROJECTION SERIES FOR THE WD
# ============================================================
make_historical_summary <- function(dat){
  
  out <- dat %>%
    filter(is.finite(value)) %>%
    group_by(year) %>%
    summarise(
      median=median(value),
      p05=quantile(value,0.05),
      p95=quantile(value,0.95),
      .groups="drop"
    )
  
  out
}

R_historical_annual <- make_historical_summary(R_historical)
SSB_historical_annual <- make_historical_summary(SSB_historical)
Catch_historical_annual <- make_historical_summary(Catch_historical)
TAC_historical_annual <- make_historical_summary(TAC_historical)
Fadv_historical_annual <- make_historical_summary(Fadv_historical)


# ============================================================
# 11. FIGURE 1 FOR THE WORKING DOCUMENT
# RECRUITMENT: HISTORICAL CONDITIONING AND MSE PROJECTION
# ============================================================

p_R <- ggplot() +
  geom_ribbon(data=R_historical_annual,aes(x=year,ymin=p05,ymax=p95),alpha=0.15) +
  geom_line(data=R_historical_annual,aes(x=year,y=median),linewidth=0.7) +
  geom_ribbon(data=annual_diagnostics,
              aes(x=year,ymin=R_p05,ymax=R_p95,fill=factor(Fcap),group=factor(Fcap)),alpha=0.15,colour=NA) +
  geom_line(data=annual_diagnostics,aes(x=year,y=R_median,colour=factor(Fcap),group=factor(Fcap)),linewidth=0.7) +
  geom_vline(xintercept=transition_year,linetype="dashed") +
  facet_wrap(~Besc,ncol=2,scales="free_y") +
  labs(x="Year",y="Age-0 recruitment",colour="Fcap",fill="Fcap") +
  theme_bw() +
  theme(legend.position="bottom",strip.background=element_blank())


# ============================================================
# 12. FIGURE 2 FOR THE WORKING DOCUMENT
# SSB: HISTORICAL CONDITIONING AND MSE PROJECTION
# ============================================================

p_SSB <- ggplot() +
  geom_ribbon(data=SSB_historical_annual,aes(x=year,ymin=p05,ymax=p95),alpha=0.15) +
  geom_line(data=SSB_historical_annual,aes(x=year,y=median),linewidth=0.7) +
  geom_ribbon(data=annual_diagnostics,
    aes(x=year,ymin=SSB_p05,ymax=SSB_p95,fill=factor(Fcap),group=factor(Fcap)), alpha=0.15,colour=NA) +
  geom_line(
    data=annual_diagnostics,
    aes(x=year,y=SSB_median,colour=factor(Fcap),group=factor(Fcap)),
    linewidth=0.7) +
  geom_vline(xintercept=transition_year,linetype="dashed") +
  geom_hline(yintercept=unique(annual_diagnostics$Blim),linetype="dashed") +
  geom_hline(yintercept=unique(annual_diagnostics$Bpa),linetype="dotted") +
  facet_wrap(~Besc,ncol=2,scales="free_y") +
  labs(x="Year",y="Spawning-stock biomass (t)",colour="Fcap",fill="Fcap") +
  theme_bw() +
  theme(legend.position="bottom",strip.background=element_blank())


# ============================================================
# 13. FIGURE 3 FOR THE WORKING DOCUMENT
# REALISED CATCH: HISTORICAL CONDITIONING AND MSE PROJECTION
# ============================================================

p_Catch <- ggplot() +
  geom_ribbon(data=Catch_historical_annual,aes(x=year,ymin=p05,ymax=p95),alpha=0.15) +
  geom_line(data=Catch_historical_annual,aes(x=year,y=median),linewidth=0.7) +
  geom_ribbon(data=annual_diagnostics,
              aes(x=year,ymin=Catch_p05,ymax=Catch_p95,fill=factor(Fcap),group=factor(Fcap)),alpha=0.15,colour=NA) +
  geom_line(data=annual_diagnostics,aes(x=year,y=Catch_median,colour=factor(Fcap),group=factor(Fcap)),linewidth=0.7) +
  geom_vline(xintercept=transition_year,linetype="dashed") +
  facet_wrap(~Besc,ncol=2,scales="free_y") +
  labs(x="Year",y="Realised catch (t)",colour="Fcap",fill="Fcap") +
  theme_bw() +
  theme(legend.position="bottom",strip.background=element_blank())


# ============================================================
# 14. FIGURE 4 FOR THE WORKING DOCUMENT
# TAC: AVAILABLE HISTORICAL ADVICE AND MSE PROJECTION
# ============================================================

p_TAC <- ggplot() +
  geom_ribbon(data=TAC_historical_annual,aes(x=year,ymin=p05,ymax=p95),alpha=0.15) +
  geom_line(data=TAC_historical_annual,aes(x=year,y=median),linewidth=0.7) +
  geom_ribbon(data=annual_diagnostics, aes(x=year,ymin=TAC_p05,ymax=TAC_p95,fill=factor(Fcap),group=factor(Fcap)),alpha=0.15,colour=NA) +
  geom_line(data=annual_diagnostics,aes(x=year,y=TAC_median,colour=factor(Fcap),group=factor(Fcap)),linewidth=0.7) +
  geom_vline(xintercept=transition_year,linetype="dashed") +
  facet_wrap(~Besc,ncol=2,scales="free_y") +
  labs(x="Year",y="TAC advice (t)",colour="Fcap",fill="Fcap") +
  theme_bw() +
  theme(legend.position="bottom",strip.background=element_blank())


# ============================================================
# 15. FIGURE 5 FOR THE WORKING DOCUMENT
# F ADVICE: AVAILABLE HISTORICAL ADVICE AND MSE PROJECTION
# ============================================================

p_Fadv <- ggplot() +
          geom_ribbon(data=Fadv_historical_annual,aes(x=year,ymin=p05,ymax=p95),alpha=0.15) +
  geom_line(data=Fadv_historical_annual,aes(x=year,y=median),linewidth=0.7) +
  geom_ribbon(data=annual_diagnostics,aes(x=year,ymin=Fadv_p05,ymax=Fadv_p95,fill=factor(Fcap),group=factor(Fcap)),alpha=0.15,colour=NA) +
  geom_line(data=annual_diagnostics,aes(x=year,y=Fadv_median,colour=factor(Fcap),group=factor(Fcap)),linewidth=0.7) +
  geom_vline(xintercept=transition_year,linetype="dashed") +
  facet_wrap(~Besc,ncol=2,scales="free_y") +
  labs(x="Year",y="F advice",colour="Fcap",fill="Fcap") +
  theme_bw() +
  theme(legend.position="bottom",strip.background=element_blank())


# ============================================================
# 16. SAVE WORKING DOCUMENT OUTPUTS
# ============================================================

write.csv(table_WD_dynamic_summary,file.path(diagnostic_dir,"21d_WD_Table1_dynamic_summary.csv"),row.names=FALSE)
write.csv(table_WD_annual_extremes,file.path(diagnostic_dir,"21d_WD_Table2_annual_extremes.csv"),row.names=FALSE)
write.csv(table_WD_extreme_trajectories,file.path(diagnostic_dir,"21d_WD_Table3_extreme_trajectories.csv"),row.names=FALSE)

ggsave(file.path(figure_dir,"21d_WD_Figure1_recruitment_history_projection.png"),p_R,width=10,height=7,dpi=300)
ggsave(file.path(figure_dir,"21d_WD_Figure2_SSB_history_projection.png"),p_SSB,width=10,height=7,dpi=300)
ggsave(file.path(figure_dir,"21d_WD_Figure3_catch_history_projection.png"),p_Catch,width=10,height=7,dpi=300)
ggsave(file.path(figure_dir,"21d_WD_Figure4_TAC_history_projection.png"),p_TAC,width=10,height=7,dpi=300)
ggsave(file.path(figure_dir,"21d_WD_Figure5_Fadv_history_projection.png"),p_Fadv,width=10,height=7,dpi=300)


# ============================================================
# 17. SAVE DIAGNOSTIC OUTPUTS
# ============================================================

write.csv(dynamic_summary,file.path(diagnostic_dir,"21d_MP_dynamic_summary.csv"),row.names=FALSE)
write.csv(annual_diagnostics,file.path(diagnostic_dir,"21d_MP_annual_diagnostics.csv"),row.names=FALSE)
write.csv(trajectory_diagnostics,file.path(diagnostic_dir,"21d_MP_trajectory_diagnostics.csv"),row.names=FALSE)
write.csv(minimum_SSB_events,file.path(diagnostic_dir,"21d_MP_minimum_SSB_events.csv"),row.names=FALSE)
write.csv(Blim_crossing_events,file.path(diagnostic_dir,"21d_MP_Blim_crossing_events.csv"),row.names=FALSE)
write.csv(closure_events,file.path(diagnostic_dir,"21d_MP_closure_events.csv"),row.names=FALSE)
write.csv(reopening_events,file.path(diagnostic_dir,"21d_MP_reopening_events.csv"),row.names=FALSE)
write.csv(extreme_trajectories,file.path(diagnostic_dir,"21d_MP_extreme_trajectories.csv"),row.names=FALSE)
write.csv(table_HCR_state,file.path(diagnostic_dir,"21d_HCR_operating_state_summary.csv"),row.names=FALSE)
write.csv(HCR_state_annual_diagnostics,file.path(diagnostic_dir,"21d_HCR_operating_state_annual.csv"),row.names=FALSE)
write.csv(table_closure_dynamics,file.path(diagnostic_dir,"21d_closure_persistence_and_switching.csv"),row.names=FALSE)

diagnostic_outputs <- list(
  scenario_grid=scenario_grid,
  dynamic_summary=dynamic_summary,
  annual_diagnostics=annual_diagnostics,
  trajectory_diagnostics=trajectory_diagnostics,
  minimum_SSB_events=minimum_SSB_events,
  Blim_crossing_events=Blim_crossing_events,
  closure_events=closure_events,
  reopening_events=reopening_events,
  extreme_trajectories=extreme_trajectories,
  HCR_state_summary=table_HCR_state,
  HCR_state_annual=HCR_state_annual_diagnostics,
  WD_table_dynamic_summary=table_WD_dynamic_summary,
  WD_table_annual_extremes=table_WD_annual_extremes,
  WD_table_extreme_trajectories=table_WD_extreme_trajectories,
  R_historical_annual=R_historical_annual,
  SSB_historical_annual=SSB_historical_annual,
  Catch_historical_annual=Catch_historical_annual,
  TAC_historical_annual=TAC_historical_annual,
  Fadv_historical_annual=Fadv_historical_annual,
  closure_persistence=closure_persistence_diagnostics,
  switching_diagnostics=switching_diagnostics,
  closure_dynamics_summary=table_closure_dynamics
)

saveRDS(diagnostic_outputs,file.path(diagnostic_dir,"21d_MP_dynamic_diagnostics.rds"))

# ============================================================
# 18. FINAL DIAGNOSTIC SUMMARY
# ============================================================

cat("\n============================================================\n")
cat("CLOSED-LOOP DYNAMIC DIAGNOSTICS COMPLETED\n")
cat("============================================================\n")

cat("Candidate MPs diagnosed:",n_scenarios,"\n")
cat("Trajectories per MP:",expected_trajectories,"\n")
cat("Projection period:",min(scenario_grid$first_projection_year),"-",max(scenario_grid$last_projection_year),"\n")
cat("Global minimum SSB:",min(dynamic_summary$min_SSB),"t\n")
cat("Global maximum Fadv:",max(dynamic_summary$max_Fadv),"\n")
cat("Global maximum TAC:",max(dynamic_summary$max_TAC),"t\n")
cat("Global maximum realised catch:",max(dynamic_summary$max_Catch),"t\n")
cat("Total Blim crossing events:",nrow(Blim_crossing_events),"\n")
cat("Total closure events:",nrow(closure_events),"\n")
cat("Total reopening events:",nrow(reopening_events),"\n")
cat("All structural checks: PASS\n")

cat("============================================================\n")
cat("Outputs saved in:",diagnostic_dir,"\n")




