# ============================================================
# 23_PLOT_CANDIDATE_MPS.R
# Figures and summary tables for candidate MP evaluation
#
# This script DOES NOT rerun FLBEIA.
# It reads performance outputs generated by:
#   22_EVALUATE_CANDIDATE_MPS.R
#
# Outputs:
#   Fig01 - Annual SSB
#   Fig02 - Annual catch
#   Fig03 - Annual risk and closures
#   Fig03b - Annual fishery status and Blim risk
#   Fig04 - SSB-catch trade-off
#   Fig05 - Catch-IAV trade-off
#   Fig06 - Catch-closure trade-off using mean annual closure probability
#   Fig07 - MP performance summary
#   Table01 - Summary of performance metrics
#
# Fig04-Fig07 and Table01 are produced for:
#   Full   = 2025-2054
#   Short  = 2025-2034
#   Medium = 2035-2044
#   Long   = 2045-2054
# ============================================================

rm(list=ls())

library(dplyr)
library(tidyr)
library(ggplot2)
library(here)

# ============================================================
# DIRECTORIES
# ============================================================

performance_file <- here("data","mse","performance","candidate_MP_performance.rds")
fig_dir <- here("outputs","mse","candidate_MPs")
table_dir <- here("outputs","mse","candidate_MPs","tables")

dir.create(fig_dir,recursive=TRUE,showWarnings=FALSE)
dir.create(table_dir,recursive=TRUE,showWarnings=FALSE)

stopifnot(file.exists(performance_file))

# ============================================================
# PARAMETERS
# ============================================================

Blim <- 4721
Bpa <- 6561
risk_threshold <- 0.05

horizon_labels <- c(
  Full="Full period (2025-2054)",
  Short="Short term (2025-2034)",
  Medium="Medium term (2035-2044)",
  Long="Long term (2045-2054)"
)

horizon_order <- c("Full","Short","Medium","Long")

# ============================================================
# LOAD PERFORMANCE OUTPUTS
# ============================================================

performance_outputs <- readRDS(performance_file)

scenario_grid <- performance_outputs$scenario_grid
performance <- performance_outputs$performance
trajectory_metrics <- performance_outputs$trajectory_metrics
annual_metrics <- performance_outputs$annual_metrics

stopifnot(nrow(scenario_grid)>0)
stopifnot(n_distinct(performance$scenario_number)==nrow(scenario_grid))
stopifnot(n_distinct(trajectory_metrics$scenario_number)==nrow(scenario_grid))
stopifnot(n_distinct(annual_metrics$scenario_number)==nrow(scenario_grid))

cat("\nCandidate MPs loaded:",nrow(scenario_grid),"\n")

# ============================================================
# SCENARIO LABEL
# ============================================================

assessment_label <- if(all(!scenario_grid$assessment_error)) "Perfect assessment" else if(all(scenario_grid$assessment_error)) "Assessment error" else "Mixed assessment error"
assessment_tag <- if(all(!scenario_grid$assessment_error)) "PERF" else if(all(scenario_grid$assessment_error)) "AE" else "MIXED"

scenario_label <- assessment_label
scenario_tag <- assessment_tag

cat("Scenario:",scenario_label,"\n")
cat("Scenario tag:",scenario_tag,"\n")

# ============================================================
# HELPERS
# ============================================================

save_mse_plot <- function(plot,filename,width=9,height=6) {
  ggsave(file.path(fig_dir,paste0(filename,".png")),plot=plot,width=width,height=height,dpi=300)
  ggsave(file.path(fig_dir,paste0(filename,".pdf")),plot=plot,width=width,height=height)
}

theme_mse <- theme_bw(base_size=12) +
  theme(panel.grid.minor=element_blank(),
        strip.background=element_blank(),
        strip.text=element_text(face="bold"),
        axis.title=element_text(face="bold"),
        legend.position="bottom",
        legend.title=element_text(face="bold"))

figure_title <- function(title,horizon=NULL) {
  if(is.null(horizon)) return(paste0(title," - ",scenario_label))
  paste0(title," - ",scenario_label," - ",horizon_labels[[horizon]])
}

output_name <- function(name,horizon=NULL) {
  if(is.null(horizon)) return(paste0(name,"_",scenario_tag))
  paste0(name,"_",scenario_tag,"_",horizon)
}

# ============================================================
# PREPARE FULL ANNUAL DATA
# ============================================================

annual_full <- annual_metrics %>% filter(horizon=="Full") %>% arrange(Fcap,Besc,year)
annual_full <- annual_full %>% mutate(Fcap_f=factor(Fcap,levels=sort(unique(Fcap))),Besc_f=factor(Besc,levels=sort(unique(Besc))))

stopifnot(all(table(annual_full$scenario_number)==30))

# ============================================================
# FIGURE 01 - ANNUAL SSB
# Full period
# ============================================================

fig01_SSB <- ggplot(annual_full,aes(x=year,y=SSB_median,group=Fcap_f)) +
  geom_ribbon(aes(ymin=SSB_p05,ymax=SSB_p95,fill=Fcap_f),alpha=0.15,colour=NA) +
  geom_line(aes(colour=Fcap_f),linewidth=0.8) +
  geom_hline(yintercept=Blim,linetype="dashed",linewidth=0.6) +
  geom_hline(yintercept=Bpa,linetype="dotted",linewidth=0.6) +
  facet_wrap(~Besc_f,ncol=1,labeller=labeller(Besc_f=function(x) paste("Besc =",x,"t"))) +
  scale_x_continuous(breaks=seq(2025,2055,5)) +
  labs(x="Year",y="Spawning stock biomass (t)",colour="Fcap",fill="Fcap",title=figure_title("Annual SSB","Full")) +
  theme_mse

print(fig01_SSB)

save_mse_plot(fig01_SSB,output_name("Fig01_annual_SSB","Full"),width=9,height=6)

# ============================================================
# FIGURE 02 - ANNUAL CATCH
# Full period
# ============================================================

fig02_catch <- ggplot(annual_full,aes(x=year,y=median_catch,group=Fcap_f)) +
  geom_ribbon(aes(ymin=p05_catch,ymax=p95_catch,fill=Fcap_f),alpha=0.15,colour=NA) +
  geom_line(aes(colour=Fcap_f),linewidth=0.8) +
  facet_wrap(~Besc_f,ncol=1,labeller=labeller(Besc_f=function(x) paste("Besc =",x,"t"))) +
  scale_x_continuous(breaks=seq(2025,2055,5)) +
  labs(x="Year",y="Catch (t)",colour="Fcap",fill="Fcap",title=figure_title("Annual catch","Full")) +
  theme_mse

print(fig02_catch)

save_mse_plot(fig02_catch,output_name("Fig02_annual_catch","Full"),width=9,height=6)

# ============================================================
# FIGURE 03 - ANNUAL RISK AND CLOSURES
# Full period
# ============================================================

annual_risk <- annual_full %>% dplyr::select(scenario_number,Fcap,Fcap_f,Besc,Besc_f,year,P_Blim,P_Bpa,P_closed) %>% 
  pivot_longer(cols=c(P_Blim,P_Bpa,P_closed),names_to="indicator",values_to="probability")
annual_risk <- annual_risk %>% mutate(indicator=factor(indicator,levels=c("P_Blim","P_Bpa","P_closed"),
                                                       labels=c("P(SSB < Blim)","P(SSB < Bpa)","P(closed)")))

fig03_risk <- ggplot(annual_risk,aes(x=year,y=probability,colour=Fcap_f,group=Fcap_f)) +
  geom_line(linewidth=0.8) +
  facet_grid(indicator~Besc_f,scales="free_y",labeller=labeller(Besc_f=function(x) paste("Besc =",x,"t"))) +
  scale_x_continuous(breaks=seq(2025,2055,5)) +
  scale_y_continuous(labels=scales::label_percent(accuracy=0.1)) +
  labs(x="Year",y="Probability",colour="Fcap",title=figure_title("Annual risk and closures","Full")) +
  theme_mse

print(fig03_risk)

save_mse_plot(fig03_risk,output_name("Fig03_annual_risk_closures","Full"),width=10,height=8)

# ============================================================
# FIGURE 03B - ANNUAL FISHERY STATUS AND BLIM RISK
# Full period
# ============================================================

annual_status <- annual_full %>% transmute(scenario_number,Fcap,Fcap_f,Besc,Besc_f,year,P_Blim,P_closed,P_open=1-P_closed)
annual_status_long <- annual_status %>% pivot_longer(cols=c(P_open,P_closed),names_to="fishery_status",values_to="proportion")
annual_status_long <- annual_status_long %>% mutate(fishery_status=factor(fishery_status,levels=c("P_closed","P_open"),labels=c("Fishery closed","Fishery open")))

fig03b_status <- ggplot() +
  geom_col(data=annual_status_long,aes(x=year,y=proportion,fill=fishery_status),position="stack",width=1) +
  geom_line(data=annual_status,aes(x=year,y=P_Blim,group=1,linetype="P(SSB < Blim)"),colour="black",linewidth=0.7) +
  geom_point(data=annual_status,aes(x=year,y=P_Blim),colour="black",size=1.4) +
  geom_hline(data=data.frame(y=risk_threshold),aes(yintercept=y,linetype="ICES risk limit (5%)"),colour="black",linewidth=0.5) +
  facet_grid(Fcap_f~Besc_f,labeller=labeller(Fcap_f=function(x) paste("Fcap =",x),Besc_f=function(x) paste("Besc =",x,"t"))) +
  scale_x_continuous(breaks=seq(2025,2055,5)) +
  scale_y_continuous(limits=c(0,1),breaks=c(0,0.05,0.25,0.50,0.75,1)) +
  scale_linetype_manual(values=c("P(SSB < Blim)"="solid","ICES risk limit (5%)"="dashed"),name=NULL) +
  labs(x="Year",y="Proportion of trajectories",fill=NULL,title=figure_title("Fishery status and Blim risk","Full")) +
  theme_mse

print(fig03b_status)

save_mse_plot(fig03b_status,output_name("Fig03b_fishery_status_Blim_risk","Full"),width=12,height=8)

# ============================================================
# SUMMARY METRICS BY HORIZON
# ============================================================

make_plot_summary <- function(horizon_name) {
  
  trajectory_h <- trajectory_metrics %>% filter(horizon==horizon_name)
  annual_h <- annual_metrics %>% filter(horizon==horizon_name)
  
  summary_trajectory_h <- trajectory_h %>%
    group_by(scenario_number,Fcap,Besc) %>%
    summarise(years_closed_median=median(n_years_closed),
              years_closed_p05=quantile(n_years_closed,0.05),
              years_closed_p95=quantile(n_years_closed,0.95),
              SSB_median=median(mean_SSB),
              SSB_p05=quantile(mean_SSB,0.05),
              SSB_p95=quantile(mean_SSB,0.95),
              SSB_open_median=median(mean_SSB_open,na.rm=TRUE),
              SSB_open_p05=quantile(mean_SSB_open,0.05,na.rm=TRUE),
              SSB_open_p95=quantile(mean_SSB_open,0.95,na.rm=TRUE),
              catch_median=median(mean_catch),
              catch_p05=quantile(mean_catch,0.05),
              catch_p95=quantile(mean_catch,0.95),
              catch_open_median=median(mean_catch_open,na.rm=TRUE),
              catch_open_p05=quantile(mean_catch_open,0.05,na.rm=TRUE),
              catch_open_p95=quantile(mean_catch_open,0.95,na.rm=TRUE),
              IAV_median=median(IAV),
              IAV_p05=quantile(IAV,0.05),
              IAV_p95=quantile(IAV,0.95),
              P_ever_closed=mean(ever_closed),
              .groups="drop")
  
  summary_risk_h <- annual_h %>%
    group_by(scenario_number,Fcap,Besc) %>%
    summarise(max_P_Blim=max(P_Blim),
              years_P_Blim_gt05=sum(P_Blim>risk_threshold),
              max_P_Bpa=max(P_Bpa),
              years_P_Bpa_gt05=sum(P_Bpa>risk_threshold),
              max_P_closed=max(P_closed),
              .groups="drop")
  
  summary_trajectory_h %>% left_join(summary_risk_h,by=c("scenario_number","Fcap","Besc")) %>% arrange(Fcap,Besc)
}

plot_summaries <- lapply(horizon_order,make_plot_summary)
names(plot_summaries) <- horizon_order

# ============================================================
# REPORT-FORMATTED TABLES
# Directly use the definitive performance metrics calculated in script 22.
# No performance metric is recalculated here.
# ============================================================

make_performance_table <- function(horizon_name) {
  performance %>%
    filter(horizon == horizon_name) %>%
    arrange(Fcap, Besc)
}

performance_tables <- lapply(horizon_order, make_performance_table)
names(performance_tables) <- horizon_order

format_performance_table <- function(x) {
  x %>%
    transmute(
      scenario_number,
      Fcap,
      Besc,
      `Max P(SSB < Blim) (%)` = sprintf("%.1f", 100 * max_P_Blim),
      `Years P(SSB < Blim) > 5%` = n_years_P_Blim_gt_5,
      `P(ever SSB < Blim) (%)` = sprintf("%.1f", 100 * P_ever_Blim),
      `Max P(SSB < Bpa) (%)` = sprintf("%.1f", 100 * max_P_Bpa),
      `Years P(SSB < Bpa) > 5%` = n_years_P_Bpa_gt_5,
      `P(ever SSB < Bpa) (%)` = sprintf("%.1f", 100 * P_ever_Bpa),
      `Mean P(closed) (%)` = sprintf("%.1f", 100 * mean_P_closed),
      `P(at least one closure) (%)` = sprintf("%.1f", 100 * P_ever_closed),
      `Mean years closed` = sprintf("%.2f", mean_years_closed),
      `Median years closed` = sprintf("%.0f", median_years_closed),
      `Mean catch (t)` = sprintf("%.0f", mean_catch),
      `Median catch (t)` = sprintf("%.0f", median_catch),
      `Mean catch in open years (t)` = sprintf("%.0f", mean_catch_open),
      `Median catch in open years (t)` = sprintf("%.0f", median_mean_catch_open),
      `Trajectories with open years` = n_trajectories_open,
      `Trajectories with open years (%)` = sprintf("%.1f", 100 * P_trajectories_open),
      `Median SSB in open years (t)` = sprintf("%.0f", median_mean_SSB_open),
      `Trajectories contributing to open-year SSB` = n_trajectories_SSB_open,
      `Trajectories contributing to open-year SSB (%)` = sprintf("%.1f", 100 * P_trajectories_SSB_open),
      `Median IAV` = sprintf("%.3f", median_IAV)
    )
}

performance_tables_report <- lapply(performance_tables, format_performance_table)

# ============================================================
# FIGURES 04-06 - TRADE-OFFS BY HORIZON
# ============================================================

make_tradeoff_plots <- function(horizon_name) {
  
  trajectory_h <- trajectory_metrics %>% filter(horizon==horizon_name)
  trajectory_h <- trajectory_h %>% mutate(Fcap_f=factor(Fcap,levels=sort(unique(scenario_grid$Fcap))),Besc_f=factor(Besc,levels=sort(unique(scenario_grid$Besc))))
  
  tradeoff_h <- trajectory_h %>%
    group_by(scenario_number,Fcap,Besc,Fcap_f,Besc_f) %>%
    summarise(SSB_open=median(mean_SSB_open,na.rm=TRUE),
              SSB_open_p05=quantile(mean_SSB_open,0.05,na.rm=TRUE),
              SSB_open_p95=quantile(mean_SSB_open,0.95,na.rm=TRUE),
              catch_open=median(mean_catch_open,na.rm=TRUE),
              catch_open_p05=quantile(mean_catch_open,0.05,na.rm=TRUE),
              catch_open_p95=quantile(mean_catch_open,0.95,na.rm=TRUE),
              catch=median(mean_catch),
              catch_p05=quantile(mean_catch,0.05),
              catch_p95=quantile(mean_catch,0.95),
              IAV=median(IAV),
              IAV_p05=quantile(IAV,0.05),
              IAV_p95=quantile(IAV,0.95),
              P_ever_closed=mean(ever_closed),
              .groups="drop")

  closure_h <- performance %>%
    filter(horizon==horizon_name) %>%
    dplyr::select(scenario_number,mean_P_closed)

  tradeoff_h <- tradeoff_h %>%
    left_join(closure_h,by="scenario_number")

  stopifnot(!any(is.na(tradeoff_h$mean_P_closed)))
  
  fig04 <- ggplot(tradeoff_h,aes(x=SSB_open,y=catch_open)) +
    geom_errorbar(aes(ymin=catch_open_p05,ymax=catch_open_p95),width=0) +
    geom_errorbarh(aes(xmin=SSB_open_p05,xmax=SSB_open_p95),height=0) +
    geom_point(aes(colour=Fcap_f),size=3) +
    facet_wrap(~Besc_f,nrow=1,labeller=labeller(Besc_f=function(x) paste("Besc =",x,"t"))) +
    labs(x="Mean SSB in open years (t)",y="Mean catch in open years (t)",colour="Fcap",title=figure_title("SSB-catch trade-off",horizon_name)) +
    theme_mse
  
  fig05 <- ggplot(tradeoff_h,aes(x=IAV,y=catch)) +
    geom_errorbar(aes(ymin=catch_p05,ymax=catch_p95),width=0) +
    geom_errorbarh(aes(xmin=IAV_p05,xmax=IAV_p95),height=0) +
    geom_point(aes(colour=Fcap_f),size=3) +
    facet_wrap(~Besc_f,nrow=1,labeller=labeller(Besc_f=function(x) paste("Besc =",x,"t"))) +
    labs(x="Interannual catch variability (IAV)",y="Mean catch (t)",colour="Fcap",title=figure_title("Catch-IAV trade-off",horizon_name)) +
    theme_mse
  
  fig06 <- ggplot(tradeoff_h,aes(x=mean_P_closed,y=catch)) +
    geom_errorbar(aes(ymin=catch_p05,ymax=catch_p95),width=0) +
    geom_point(aes(colour=Fcap_f),size=3) +
    facet_wrap(~Besc_f,nrow=1,labeller=labeller(Besc_f=function(x) paste("Besc =",x,"t"))) +
    scale_x_continuous(labels=scales::label_percent(accuracy=1)) +
    labs(x="Mean probability of fishery closure",y="Mean catch (t)",colour="Fcap",title=figure_title("Catch-closure trade-off",horizon_name)) +
    theme_mse
  
  list(fig04=fig04,fig05=fig05,fig06=fig06)
}

tradeoff_plots <- lapply(horizon_order,make_tradeoff_plots)
names(tradeoff_plots) <- horizon_order

# ============================================================
# FIGURE 07 - MP PERFORMANCE SUMMARY BY HORIZON
# Columns = Besc
# Colours = Fcap
# ============================================================

metric_levels <- c(
  "Max P(SSB < Blim)",
  "Years P(SSB < Blim) > 5%",
  "P(at least one closure)",
  "Years fishery closed",
  "Catch in open years (t)",
  "SSB, all years (t)",
  "SSB, open years (t)",
  "IAV"
)

make_performance_plot <- function(horizon_name) {
  
  summary_h <- plot_summaries[[horizon_name]] %>%
    mutate(Fcap_f=factor(Fcap,levels=sort(unique(scenario_grid$Fcap))),
           Besc_f=factor(Besc,levels=sort(unique(scenario_grid$Besc))))
  
  plot_h <- bind_rows(
    summary_h %>% transmute(Fcap_f,Besc_f,metric="Max P(SSB < Blim)",value=100*max_P_Blim,lower=NA_real_,upper=NA_real_),
    summary_h %>% transmute(Fcap_f,Besc_f,metric="Years P(SSB < Blim) > 5%",value=years_P_Blim_gt05,lower=NA_real_,upper=NA_real_),
    summary_h %>% transmute(Fcap_f,Besc_f,metric="P(at least one closure)",value=100*P_ever_closed,lower=NA_real_,upper=NA_real_),
    summary_h %>% transmute(Fcap_f,Besc_f,metric="Years fishery closed",value=years_closed_median,lower=years_closed_p05,upper=years_closed_p95),
    summary_h %>% transmute(Fcap_f,Besc_f,metric="Catch in open years (t)",value=catch_open_median,lower=catch_open_p05,upper=catch_open_p95),
    summary_h %>% transmute(Fcap_f,Besc_f,metric="SSB, all years (t)",value=SSB_median,lower=SSB_p05,upper=SSB_p95),
    summary_h %>% transmute(Fcap_f,Besc_f,metric="SSB, open years (t)",value=SSB_open_median,lower=SSB_open_p05,upper=SSB_open_p95),
    summary_h %>% transmute(Fcap_f,Besc_f,metric="IAV",value=IAV_median,lower=IAV_p05,upper=IAV_p95)
  )
  
  plot_h <- plot_h %>% mutate(metric=factor(metric,levels=metric_levels))
  
  ICES_risk_line <- expand.grid(metric=factor("Max P(SSB < Blim)",levels=metric_levels),Besc_f=levels(plot_h$Besc_f),y=5)
  
  ggplot(plot_h,aes(x=Fcap_f,y=value,colour=Fcap_f)) +
    geom_hline(data=ICES_risk_line,aes(yintercept=y),inherit.aes=FALSE,linetype="dashed",linewidth=0.5) +
    geom_errorbar(aes(ymin=lower,ymax=upper),width=0,linewidth=0.6,na.rm=TRUE) +
    geom_point(size=3) +
    facet_grid(metric~Besc_f,scales="free_y",labeller=labeller(Besc_f=function(x) paste("Besc =",x,"t"))) +
    labs(x=NULL,y=NULL,colour="Fcap",title=figure_title("MP performance",horizon_name)) +
    theme_mse +
    theme(strip.text.y=element_text(angle=0),strip.placement="outside",legend.position="bottom")
}

performance_plots <- lapply(horizon_order,make_performance_plot)
names(performance_plots) <- horizon_order

# ============================================================
# PRINT FIGURES 04-07
# ============================================================

for(h in horizon_order) {
  print(tradeoff_plots[[h]]$fig04)
  print(tradeoff_plots[[h]]$fig05)
  print(tradeoff_plots[[h]]$fig06)
  print(performance_plots[[h]])
}

# ============================================================
# SAVE FIGURES 04-07
# ============================================================

for(h in horizon_order) {
  save_mse_plot(tradeoff_plots[[h]]$fig04,output_name("Fig04_SSB_catch_tradeoff",h),width=10,height=5)
  save_mse_plot(tradeoff_plots[[h]]$fig05,output_name("Fig05_catch_IAV_tradeoff",h),width=10,height=5)
  save_mse_plot(tradeoff_plots[[h]]$fig06,output_name("Fig06_catch_closure_tradeoff",h),width=10,height=5)
  save_mse_plot(performance_plots[[h]],output_name("Fig07_MP_performance",h),width=12,height=12)
}

# ============================================================
# SAVE TABLES
# ============================================================

for(h in horizon_order) {
  write.csv(performance_tables[[h]],file.path(table_dir,paste0("Table01_performance_",scenario_tag,"_",h,"_numeric.csv")),row.names=FALSE)
  write.csv(performance_tables_report[[h]],file.path(table_dir,paste0("Table01_performance_",scenario_tag,"_",h,"_report.csv")),row.names=FALSE)
}

# ============================================================
# FINAL CHECKS
# ============================================================

stopifnot(all(vapply(performance_tables,nrow,integer(1))==nrow(scenario_grid)))
stopifnot(all(vapply(performance_tables_report,nrow,integer(1))==nrow(scenario_grid)))
stopifnot(all(vapply(performance_tables,function(x) all(x$max_P_Blim>=0 & x$max_P_Blim<=1),logical(1))))
stopifnot(all(vapply(performance_tables,function(x) all(x$max_P_Bpa>=0 & x$max_P_Bpa<=1),logical(1))))
stopifnot(all(vapply(performance_tables,function(x) all(x$P_ever_closed>=0 & x$P_ever_closed<=1),logical(1))))

# ============================================================
# SUMMARY
# ============================================================

cat("\n============================================================\n")
cat("CANDIDATE MP FIGURES AND TABLES COMPLETED\n")
cat("============================================================\n")
cat("Scenario:",scenario_label,"\n")
cat("Scenario tag:",scenario_tag,"\n")
cat("Candidate MPs:",nrow(scenario_grid),"\n")
cat("Fcap values:",paste(sort(unique(scenario_grid$Fcap)),collapse=", "),"\n")
cat("Besc values:",paste(sort(unique(scenario_grid$Besc)),collapse=", "),"\n")
cat("Horizons:",paste(horizon_order,collapse=", "),"\n")
cat("Figures:",fig_dir,"\n")
cat("Tables:",table_dir,"\n")